# Generated by Django 5.2.9 on 2026-02-14 13:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_remove_employeeconfiguration_require_employee_consent_cross_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer_id', models.IntegerField(db_index=True)),
                ('tenant_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(choices=[('ANNOUNCEMENT', 'Announcement'), ('POLICY_UPDATE', 'Policy Update'), ('HR_LETTER', 'HR Letter')], max_length=30)),
                ('letter_type', models.CharField(choices=[('NONE', 'None'), ('QUERY', 'Query Letter'), ('WARNING', 'Warning Letter')], default='NONE', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High'), ('EMERGENCY', 'Emergency')], default='NORMAL', max_length=20)),
                ('visibility', models.CharField(choices=[('TARGETED', 'Targeted'), ('PRIVATE', 'Private')], default='TARGETED', max_length=20)),
                ('allow_comments', models.BooleanField(default=False)),
                ('requires_ack', models.BooleanField(default=False)),
                ('allow_response', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('SENT', 'Sent'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Closed')], db_index=True, default='DRAFT', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_id', models.IntegerField(db_index=True)),
                ('updated_by_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'communications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('recipient_role', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('MANAGER', 'Manager'), ('HR', 'HR')], default='EMPLOYEE', max_length=20)),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('ack_required', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('response_required', models.BooleanField(default=False)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('SENT', 'Sent'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESPONDED', 'Responded'), ('CLOSED', 'Closed')], default='SENT', max_length=20)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='communications.communication')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='employees.employee')),
            ],
            options={
                'db_table': 'communication_recipients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='communications.communication')),
                ('recipient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='communications.communicationrecipient')),
            ],
            options={
                'db_table': 'communication_responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_type', models.CharField(choices=[('ALL', 'All Employees'), ('DEPARTMENT', 'Department'), ('BRANCH', 'Branch'), ('LOCATION', 'Location'), ('JOB_TITLE', 'Job Title'), ('EMPLOYMENT_STATUS', 'Employment Status'), ('EMPLOYEE_ID', 'Employee'), ('RBAC_ROLE', 'RBAC Role')], max_length=30)),
                ('rule_value', models.JSONField(blank=True, default=dict)),
                ('include', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='communications.communication')),
            ],
            options={
                'db_table': 'communication_targets',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer_id', models.IntegerField(db_index=True)),
                ('tenant_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('QUERY', 'Query Letter'), ('WARNING', 'Warning Letter')], max_length=20)),
                ('subject_template', models.TextField()),
                ('body_template', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'communication_templates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employer_id', 'template_type'], name='communicati_employe_9717c5_idx')],
                'unique_together': {('employer_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CommunicationTemplateVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_label', models.CharField(blank=True, max_length=50, null=True)),
                ('subject_template', models.TextField()),
                ('body_template', models.TextField()),
                ('created_by_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='communications.communicationtemplate')),
            ],
            options={
                'db_table': 'communication_template_versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('change_reason', models.TextField(blank=True, null=True)),
                ('is_correction', models.BooleanField(default=False)),
                ('checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('created_by_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='communications.communication')),
                ('supersedes_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='communications.communicationversion')),
            ],
            options={
                'db_table': 'communication_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='communication_attachments/')),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('original_name', models.CharField(blank=True, max_length=255, null=True)),
                ('checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('virus_scan_status', models.CharField(choices=[('PENDING', 'Pending'), ('CLEAN', 'Clean'), ('INFECTED', 'Infected'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('uploaded_by_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='communications.communication')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='communications.communicationversion')),
            ],
            options={
                'db_table': 'communication_attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='communication',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='communications.communicationversion'),
        ),
        migrations.CreateModel(
            name='CommunicationAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('actor_user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('actor_employee_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='communications.communication')),
            ],
            options={
                'db_table': 'communication_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['communication', 'created_at'], name='communicati_communi_72cf9f_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommunicationComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('body', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='communications.communication')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_comments', to='employees.employee')),
            ],
            options={
                'db_table': 'communication_comments',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['communication', 'created_at'], name='communicati_communi_c43978_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='communicationrecipient',
            index=models.Index(fields=['communication', 'employee'], name='communicati_communi_7e37fe_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationrecipient',
            index=models.Index(fields=['user_id'], name='communicati_user_id_2ff46d_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationrecipient',
            index=models.Index(fields=['state'], name='communicati_state_be80c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='communicationrecipient',
            unique_together={('communication', 'employee', 'recipient_role')},
        ),
        migrations.AddIndex(
            model_name='communicationtarget',
            index=models.Index(fields=['rule_type'], name='communicati_rule_ty_115a05_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='communicationversion',
            unique_together={('communication', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='communicationattachment',
            index=models.Index(fields=['communication', 'uploaded_at'], name='communicati_communi_e113c0_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['employer_id', 'status'], name='communicati_employe_e52020_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['employer_id', 'type'], name='communicati_employe_5009ef_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['scheduled_at'], name='communicati_schedul_933f06_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['sent_at'], name='communicati_sent_at_eed327_idx'),
        ),
    ]
