"""Default RBAC permission catalog for employer modules."""
from .models import Permission


DEFAULT_PERMISSIONS = [
    {
        "code": "employer.dashboard.view",
        "module": "employer",
        "resource": "dashboard",
        "action": "view",
        "scope": "COMPANY",
        "description": "View employer dashboard.",
    },
    {
        "code": "employer.config.manage",
        "module": "employer",
        "resource": "configuration",
        "action": "manage",
        "scope": "COMPANY",
        "description": "Manage employer configuration (branches, departments, policies).",
    },
    {
        "code": "employees.manage",
        "module": "employees",
        "resource": "employee",
        "action": "manage",
        "scope": "COMPANY",
        "description": "Manage employees and profiles.",
    },
    {
        "code": "employees.configure",
        "module": "employees",
        "resource": "configuration",
        "action": "manage",
        "scope": "COMPANY",
        "description": "Manage employee setup, branches, and departments.",
    },
    {
        "code": "contracts.manage",
        "module": "contracts",
        "resource": "contract",
        "action": "manage",
        "scope": "COMPANY",
        "description": "Manage contracts.",
    },
    {
        "code": "timeoff.manage",
        "module": "timeoff",
        "resource": "timeoff",
        "action": "manage",
        "scope": "COMPANY",
        "description": "Manage time-off requests and configuration.",
    },
    {
        "code": "attendance.manage",
        "module": "attendance",
        "resource": "attendance",
        "action": "manage",
        "scope": "COMPANY",
        "description": "Manage attendance settings and records.",
    },
    {
        "code": "income_expense.manage",
        "module": "income_expense",
        "resource": "income_expense",
        "action": "manage",
        "scope": "COMPANY",
        "description": "Manage income and expense workflows.",
    },
    {
        "code": "treasury.manage",
        "module": "treasury",
        "resource": "treasury",
        "action": "manage",
        "scope": "COMPANY",
        "description": "Manage treasury operations.",
    },
    {
        "code": "billing.manage",
        "module": "billing",
        "resource": "billing",
        "action": "manage",
        "scope": "COMPANY",
        "description": "Manage billing operations.",
    },
    {
        "code": "billing.gbpay.view",
        "module": "billing",
        "resource": "gbpay_connection",
        "action": "view",
        "scope": "COMPANY",
        "description": "View GbPay connections.",
    },
    {
        "code": "billing.gbpay.manage",
        "module": "billing",
        "resource": "gbpay_connection",
        "action": "manage",
        "scope": "COMPANY",
        "description": "Manage GbPay connections.",
    },
    {
        "code": "billing.funding.view",
        "module": "billing",
        "resource": "funding_method",
        "action": "view",
        "scope": "COMPANY",
        "description": "View employer funding methods.",
    },
    {
        "code": "billing.funding.create",
        "module": "billing",
        "resource": "funding_method",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create employer funding methods.",
    },
    {
        "code": "billing.funding.update",
        "module": "billing",
        "resource": "funding_method",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update employer funding methods.",
    },
    {
        "code": "billing.funding.delete",
        "module": "billing",
        "resource": "funding_method",
        "action": "delete",
        "scope": "COMPANY",
        "description": "Delete employer funding methods.",
    },
    {
        "code": "billing.plan.view",
        "module": "billing",
        "resource": "plan",
        "action": "view",
        "scope": "COMPANY",
        "description": "View billing plans.",
    },
    {
        "code": "billing.plan.create",
        "module": "billing",
        "resource": "plan",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create billing plans.",
    },
    {
        "code": "billing.plan.update",
        "module": "billing",
        "resource": "plan",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update billing plans.",
    },
    {
        "code": "billing.plan.delete",
        "module": "billing",
        "resource": "plan",
        "action": "delete",
        "scope": "COMPANY",
        "description": "Delete billing plans.",
    },
    {
        "code": "billing.subscription.view",
        "module": "billing",
        "resource": "subscription",
        "action": "view",
        "scope": "COMPANY",
        "description": "View subscriptions.",
    },
    {
        "code": "billing.subscription.create",
        "module": "billing",
        "resource": "subscription",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create subscriptions.",
    },
    {
        "code": "billing.subscription.update",
        "module": "billing",
        "resource": "subscription",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update subscriptions.",
    },
    {
        "code": "billing.subscription.cancel",
        "module": "billing",
        "resource": "subscription",
        "action": "cancel",
        "scope": "COMPANY",
        "description": "Cancel subscriptions.",
    },
    {
        "code": "billing.subscription.charge",
        "module": "billing",
        "resource": "subscription",
        "action": "charge",
        "scope": "COMPANY",
        "description": "Charge subscription invoices.",
    },
    {
        "code": "billing.invoice.view",
        "module": "billing",
        "resource": "invoice",
        "action": "view",
        "scope": "COMPANY",
        "description": "View invoices.",
    },
    {
        "code": "billing.invoice.update",
        "module": "billing",
        "resource": "invoice",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update invoice payment state.",
    },
    {
        "code": "billing.transaction.view",
        "module": "billing",
        "resource": "transaction",
        "action": "view",
        "scope": "COMPANY",
        "description": "View billing transactions.",
    },
    {
        "code": "billing.transaction.refund",
        "module": "billing",
        "resource": "transaction",
        "action": "refund",
        "scope": "COMPANY",
        "description": "Refund billing transactions.",
    },
    {
        "code": "billing.payout.view",
        "module": "billing",
        "resource": "payout",
        "action": "view",
        "scope": "COMPANY",
        "description": "View payouts.",
    },
    {
        "code": "billing.payout.create",
        "module": "billing",
        "resource": "payout",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create payouts.",
    },
    {
        "code": "billing.payout.update",
        "module": "billing",
        "resource": "payout",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update payouts.",
    },
    {
        "code": "fleets.manage",
        "module": "fleets",
        "resource": "fleet",
        "action": "manage",
        "scope": "COMPANY",
        "description": "Manage fleet operations.",
    },
    {
        "code": "frontdesk.manage",
        "module": "frontdesk",
        "resource": "frontdesk",
        "action": "manage",
        "scope": "COMPANY",
        "description": "Manage frontdesk operations.",
    },
    {
        "code": "recruitment.manage",
        "module": "recruitment",
        "resource": "recruitment",
        "action": "manage",
        "scope": "COMPANY",
        "description": "Manage recruitment module settings and workflows.",
    },
    {
        "code": "recruitment.job.view",
        "module": "recruitment",
        "resource": "job",
        "action": "view",
        "scope": "COMPANY",
        "description": "View job positions.",
    },
    {
        "code": "recruitment.job.create",
        "module": "recruitment",
        "resource": "job",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create job positions.",
    },
    {
        "code": "recruitment.job.update",
        "module": "recruitment",
        "resource": "job",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update job positions.",
    },
    {
        "code": "recruitment.job.delete",
        "module": "recruitment",
        "resource": "job",
        "action": "delete",
        "scope": "COMPANY",
        "description": "Archive or delete job positions.",
    },
    {
        "code": "recruitment.job.publish",
        "module": "recruitment",
        "resource": "job",
        "action": "publish",
        "scope": "COMPANY",
        "description": "Publish or unpublish job positions.",
    },
    {
        "code": "recruitment.applicant.view",
        "module": "recruitment",
        "resource": "applicant",
        "action": "view",
        "scope": "COMPANY",
        "description": "View recruitment applicants.",
    },
    {
        "code": "recruitment.applicant.create",
        "module": "recruitment",
        "resource": "applicant",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create recruitment applicants.",
    },
    {
        "code": "recruitment.applicant.update",
        "module": "recruitment",
        "resource": "applicant",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update recruitment applicants.",
    },
    {
        "code": "recruitment.applicant.move_stage",
        "module": "recruitment",
        "resource": "applicant",
        "action": "move_stage",
        "scope": "COMPANY",
        "description": "Move applicants between stages.",
    },
    {
        "code": "recruitment.applicant.refuse",
        "module": "recruitment",
        "resource": "applicant",
        "action": "refuse",
        "scope": "COMPANY",
        "description": "Refuse applicants.",
    },
    {
        "code": "recruitment.stage.view",
        "module": "recruitment",
        "resource": "stage",
        "action": "view",
        "scope": "COMPANY",
        "description": "View recruitment stages.",
    },
    {
        "code": "recruitment.stage.manage",
        "module": "recruitment",
        "resource": "stage",
        "action": "manage",
        "scope": "COMPANY",
        "description": "Manage recruitment stages.",
    },
    {
        "code": "recruitment.refuse_reason.view",
        "module": "recruitment",
        "resource": "refuse_reason",
        "action": "view",
        "scope": "COMPANY",
        "description": "View recruitment refusal reasons.",
    },
    {
        "code": "recruitment.refuse_reason.manage",
        "module": "recruitment",
        "resource": "refuse_reason",
        "action": "manage",
        "scope": "COMPANY",
        "description": "Manage recruitment refusal reasons.",
    },
    {
        "code": "recruitment.report.view",
        "module": "recruitment",
        "resource": "report",
        "action": "view",
        "scope": "COMPANY",
        "description": "View recruitment reports.",
    },
    {
        "code": "recruitment.settings.view",
        "module": "recruitment",
        "resource": "settings",
        "action": "view",
        "scope": "COMPANY",
        "description": "View recruitment settings.",
    },
    {
        "code": "recruitment.settings.update",
        "module": "recruitment",
        "resource": "settings",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update recruitment settings.",
    },
    {
        "code": "reports.view",
        "module": "reports",
        "resource": "reports",
        "action": "view",
        "scope": "COMPANY",
        "description": "View employer reports.",
    },
    # Employees (action-level)
    {
        "code": "employees.employee.view",
        "module": "employees",
        "resource": "employee",
        "action": "view",
        "scope": "COMPANY",
        "description": "View employee profiles and details.",
    },
    {
        "code": "employees.employee.create",
        "module": "employees",
        "resource": "employee",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create new employees.",
    },
    {
        "code": "employees.employee.update",
        "module": "employees",
        "resource": "employee",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update employee profiles and status.",
    },
    {
        "code": "employees.employee.delete",
        "module": "employees",
        "resource": "employee",
        "action": "delete",
        "scope": "COMPANY",
        "description": "Delete employee records.",
    },
    {
        "code": "employees.employee.invite",
        "module": "employees",
        "resource": "employee",
        "action": "invite",
        "scope": "COMPANY",
        "description": "Send or resend employee invitations.",
    },
    {
        "code": "employees.employee.terminate",
        "module": "employees",
        "resource": "employee",
        "action": "terminate",
        "scope": "COMPANY",
        "description": "Terminate employee employment.",
    },
    {
        "code": "employees.employee.credentials",
        "module": "employees",
        "resource": "employee",
        "action": "credentials",
        "scope": "COMPANY",
        "description": "Manage employee attendance credentials.",
    },
    {
        "code": "employees.document.upload",
        "module": "employees",
        "resource": "document",
        "action": "upload",
        "scope": "COMPANY",
        "description": "Upload employee documents.",
    },
    {
        "code": "employees.department.view",
        "module": "employees",
        "resource": "department",
        "action": "view",
        "scope": "COMPANY",
        "description": "View departments.",
    },
    {
        "code": "employees.department.create",
        "module": "employees",
        "resource": "department",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create departments.",
    },
    {
        "code": "employees.department.update",
        "module": "employees",
        "resource": "department",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update departments.",
    },
    {
        "code": "employees.department.delete",
        "module": "employees",
        "resource": "department",
        "action": "delete",
        "scope": "COMPANY",
        "description": "Delete departments.",
    },
    {
        "code": "employees.branch.view",
        "module": "employees",
        "resource": "branch",
        "action": "view",
        "scope": "COMPANY",
        "description": "View branches.",
    },
    {
        "code": "employees.branch.create",
        "module": "employees",
        "resource": "branch",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create branches.",
    },
    {
        "code": "employees.branch.update",
        "module": "employees",
        "resource": "branch",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update branches.",
    },
    {
        "code": "employees.branch.delete",
        "module": "employees",
        "resource": "branch",
        "action": "delete",
        "scope": "COMPANY",
        "description": "Delete branches.",
    },
    {
        "code": "employees.configuration.view",
        "module": "employees",
        "resource": "configuration",
        "action": "view",
        "scope": "COMPANY",
        "description": "View employee configuration.",
    },
    {
        "code": "employees.configuration.update",
        "module": "employees",
        "resource": "configuration",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update employee configuration.",
    },
    {
        "code": "employees.termination_approval.view",
        "module": "employees",
        "resource": "termination_approval",
        "action": "view",
        "scope": "COMPANY",
        "description": "View termination approval requests.",
    },
    {
        "code": "employees.termination_approval.approve",
        "module": "employees",
        "resource": "termination_approval",
        "action": "approve",
        "scope": "COMPANY",
        "description": "Approve termination requests.",
    },
    {
        "code": "employees.termination_approval.reject",
        "module": "employees",
        "resource": "termination_approval",
        "action": "reject",
        "scope": "COMPANY",
        "description": "Reject termination requests.",
    },
    # Contracts (action-level)
    {
        "code": "contracts.contract.view",
        "module": "contracts",
        "resource": "contract",
        "action": "view",
        "scope": "COMPANY",
        "description": "View contracts.",
    },
    {
        "code": "contracts.contract.create",
        "module": "contracts",
        "resource": "contract",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create contracts.",
    },
    {
        "code": "contracts.contract.update",
        "module": "contracts",
        "resource": "contract",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update contracts.",
    },
    {
        "code": "contracts.contract.delete",
        "module": "contracts",
        "resource": "contract",
        "action": "delete",
        "scope": "COMPANY",
        "description": "Delete contracts.",
    },
    {
        "code": "contracts.contract.approve",
        "module": "contracts",
        "resource": "contract",
        "action": "approve",
        "scope": "COMPANY",
        "description": "Approve contracts.",
    },
    {
        "code": "contracts.contract.send_for_approval",
        "module": "contracts",
        "resource": "contract",
        "action": "send_for_approval",
        "scope": "COMPANY",
        "description": "Send contracts for approval.",
    },
    {
        "code": "contracts.contract.send_for_signature",
        "module": "contracts",
        "resource": "contract",
        "action": "send_for_signature",
        "scope": "COMPANY",
        "description": "Send contracts for signature.",
    },
    {
        "code": "contracts.contract.generate_document",
        "module": "contracts",
        "resource": "contract",
        "action": "generate_document",
        "scope": "COMPANY",
        "description": "Generate contract documents.",
    },
    {
        "code": "contracts.contract.sign",
        "module": "contracts",
        "resource": "contract",
        "action": "sign",
        "scope": "COMPANY",
        "description": "Sign contracts.",
    },
    {
        "code": "contracts.contract.renew",
        "module": "contracts",
        "resource": "contract",
        "action": "renew",
        "scope": "COMPANY",
        "description": "Renew contracts.",
    },
    {
        "code": "contracts.contract.terminate",
        "module": "contracts",
        "resource": "contract",
        "action": "terminate",
        "scope": "COMPANY",
        "description": "Terminate contracts.",
    },
    {
        "code": "contracts.contract.activate",
        "module": "contracts",
        "resource": "contract",
        "action": "activate",
        "scope": "COMPANY",
        "description": "Activate contracts.",
    },
    {
        "code": "contracts.contract.expire",
        "module": "contracts",
        "resource": "contract",
        "action": "expire",
        "scope": "COMPANY",
        "description": "Expire contracts.",
    },
    {
        "code": "contracts.template.view",
        "module": "contracts",
        "resource": "template",
        "action": "view",
        "scope": "COMPANY",
        "description": "View contract templates.",
    },
    {
        "code": "contracts.template.update",
        "module": "contracts",
        "resource": "template",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update contract templates.",
    },
    {
        "code": "contracts.configuration.view",
        "module": "contracts",
        "resource": "configuration",
        "action": "view",
        "scope": "COMPANY",
        "description": "View contract configuration.",
    },
    {
        "code": "contracts.configuration.update",
        "module": "contracts",
        "resource": "configuration",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update contract configuration.",
    },
    {
        "code": "contracts.salary_scale.view",
        "module": "contracts",
        "resource": "salary_scale",
        "action": "view",
        "scope": "COMPANY",
        "description": "View salary scales.",
    },
    {
        "code": "contracts.salary_scale.create",
        "module": "contracts",
        "resource": "salary_scale",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create salary scales.",
    },
    {
        "code": "contracts.salary_scale.update",
        "module": "contracts",
        "resource": "salary_scale",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update salary scales.",
    },
    {
        "code": "contracts.salary_scale.delete",
        "module": "contracts",
        "resource": "salary_scale",
        "action": "delete",
        "scope": "COMPANY",
        "description": "Delete salary scales.",
    },
    # Time off (action-level)
    {
        "code": "timeoff.configuration.view",
        "module": "timeoff",
        "resource": "configuration",
        "action": "view",
        "scope": "COMPANY",
        "description": "View time off configuration.",
    },
    {
        "code": "timeoff.configuration.update",
        "module": "timeoff",
        "resource": "configuration",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update time off configuration.",
    },
    {
        "code": "timeoff.type.view",
        "module": "timeoff",
        "resource": "type",
        "action": "view",
        "scope": "COMPANY",
        "description": "View time off types.",
    },
    {
        "code": "timeoff.type.create",
        "module": "timeoff",
        "resource": "type",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create time off types.",
    },
    {
        "code": "timeoff.type.update",
        "module": "timeoff",
        "resource": "type",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update time off types.",
    },
    {
        "code": "timeoff.type.delete",
        "module": "timeoff",
        "resource": "type",
        "action": "delete",
        "scope": "COMPANY",
        "description": "Delete time off types.",
    },
    {
        "code": "timeoff.request.view",
        "module": "timeoff",
        "resource": "request",
        "action": "view",
        "scope": "COMPANY",
        "description": "View time off requests.",
    },
    {
        "code": "timeoff.request.create",
        "module": "timeoff",
        "resource": "request",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create time off requests.",
    },
    {
        "code": "timeoff.request.update",
        "module": "timeoff",
        "resource": "request",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update time off requests.",
    },
    {
        "code": "timeoff.request.delete",
        "module": "timeoff",
        "resource": "request",
        "action": "delete",
        "scope": "COMPANY",
        "description": "Delete time off requests.",
    },
    {
        "code": "timeoff.request.submit",
        "module": "timeoff",
        "resource": "request",
        "action": "submit",
        "scope": "COMPANY",
        "description": "Submit time off requests.",
    },
    {
        "code": "timeoff.request.approve",
        "module": "timeoff",
        "resource": "request",
        "action": "approve",
        "scope": "COMPANY",
        "description": "Approve time off requests.",
    },
    {
        "code": "timeoff.request.reject",
        "module": "timeoff",
        "resource": "request",
        "action": "reject",
        "scope": "COMPANY",
        "description": "Reject time off requests.",
    },
    {
        "code": "timeoff.request.cancel",
        "module": "timeoff",
        "resource": "request",
        "action": "cancel",
        "scope": "COMPANY",
        "description": "Cancel time off requests.",
    },
    {
        "code": "timeoff.allocation.view",
        "module": "timeoff",
        "resource": "allocation",
        "action": "view",
        "scope": "COMPANY",
        "description": "View time off allocations.",
    },
    {
        "code": "timeoff.allocation.create",
        "module": "timeoff",
        "resource": "allocation",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create time off allocations.",
    },
    {
        "code": "timeoff.allocation.update",
        "module": "timeoff",
        "resource": "allocation",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update time off allocations.",
    },
    {
        "code": "timeoff.allocation.delete",
        "module": "timeoff",
        "resource": "allocation",
        "action": "delete",
        "scope": "COMPANY",
        "description": "Delete time off allocations.",
    },
    {
        "code": "timeoff.allocation.bulk",
        "module": "timeoff",
        "resource": "allocation",
        "action": "bulk",
        "scope": "COMPANY",
        "description": "Bulk allocate time off.",
    },
    {
        "code": "timeoff.allocation.confirm",
        "module": "timeoff",
        "resource": "allocation",
        "action": "confirm",
        "scope": "COMPANY",
        "description": "Confirm time off allocations.",
    },
    {
        "code": "timeoff.allocation.cancel",
        "module": "timeoff",
        "resource": "allocation",
        "action": "cancel",
        "scope": "COMPANY",
        "description": "Cancel time off allocations.",
    },
    {
        "code": "timeoff.allocation.approve",
        "module": "timeoff",
        "resource": "allocation_request",
        "action": "approve",
        "scope": "COMPANY",
        "description": "Approve allocation requests.",
    },
    {
        "code": "timeoff.allocation.reject",
        "module": "timeoff",
        "resource": "allocation_request",
        "action": "reject",
        "scope": "COMPANY",
        "description": "Reject allocation requests.",
    },
    {
        "code": "timeoff.accrual.run",
        "module": "timeoff",
        "resource": "accrual",
        "action": "run",
        "scope": "COMPANY",
        "description": "Run time off accruals.",
    },
    # Attendance (action-level)
    {
        "code": "attendance.record.view",
        "module": "attendance",
        "resource": "record",
        "action": "view",
        "scope": "COMPANY",
        "description": "View attendance records.",
    },
    {
        "code": "attendance.record.create",
        "module": "attendance",
        "resource": "record",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create attendance records manually.",
    },
    {
        "code": "attendance.record.approve",
        "module": "attendance",
        "resource": "record",
        "action": "approve",
        "scope": "COMPANY",
        "description": "Approve attendance records.",
    },
    {
        "code": "attendance.record.refuse",
        "module": "attendance",
        "resource": "record",
        "action": "refuse",
        "scope": "COMPANY",
        "description": "Refuse attendance records.",
    },
    {
        "code": "attendance.record.partial_approve",
        "module": "attendance",
        "resource": "record",
        "action": "partial_approve",
        "scope": "COMPANY",
        "description": "Partially approve attendance records.",
    },
    {
        "code": "attendance.configuration.view",
        "module": "attendance",
        "resource": "configuration",
        "action": "view",
        "scope": "COMPANY",
        "description": "View attendance configuration.",
    },
    {
        "code": "attendance.configuration.update",
        "module": "attendance",
        "resource": "configuration",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update attendance configuration.",
    },
    {
        "code": "attendance.site.view",
        "module": "attendance",
        "resource": "site",
        "action": "view",
        "scope": "COMPANY",
        "description": "View attendance sites.",
    },
    {
        "code": "attendance.site.create",
        "module": "attendance",
        "resource": "site",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create attendance sites.",
    },
    {
        "code": "attendance.site.update",
        "module": "attendance",
        "resource": "site",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update attendance sites.",
    },
    {
        "code": "attendance.site.delete",
        "module": "attendance",
        "resource": "site",
        "action": "delete",
        "scope": "COMPANY",
        "description": "Delete attendance sites.",
    },
    {
        "code": "attendance.wifi.view",
        "module": "attendance",
        "resource": "wifi",
        "action": "view",
        "scope": "COMPANY",
        "description": "View allowed Wi-Fi networks.",
    },
    {
        "code": "attendance.wifi.create",
        "module": "attendance",
        "resource": "wifi",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create allowed Wi-Fi networks.",
    },
    {
        "code": "attendance.wifi.update",
        "module": "attendance",
        "resource": "wifi",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update allowed Wi-Fi networks.",
    },
    {
        "code": "attendance.wifi.delete",
        "module": "attendance",
        "resource": "wifi",
        "action": "delete",
        "scope": "COMPANY",
        "description": "Delete allowed Wi-Fi networks.",
    },
    {
        "code": "attendance.kiosk.view",
        "module": "attendance",
        "resource": "kiosk",
        "action": "view",
        "scope": "COMPANY",
        "description": "View kiosk stations.",
    },
    {
        "code": "attendance.kiosk.create",
        "module": "attendance",
        "resource": "kiosk",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create kiosk stations.",
    },
    {
        "code": "attendance.kiosk.update",
        "module": "attendance",
        "resource": "kiosk",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update kiosk stations.",
    },
    {
        "code": "attendance.kiosk.delete",
        "module": "attendance",
        "resource": "kiosk",
        "action": "delete",
        "scope": "COMPANY",
        "description": "Delete kiosk stations.",
    },
    {
        "code": "attendance.schedule.view",
        "module": "attendance",
        "resource": "schedule",
        "action": "view",
        "scope": "COMPANY",
        "description": "View working schedules.",
    },
    {
        "code": "attendance.schedule.create",
        "module": "attendance",
        "resource": "schedule",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create working schedules.",
    },
    {
        "code": "attendance.schedule.update",
        "module": "attendance",
        "resource": "schedule",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update working schedules.",
    },
    {
        "code": "attendance.schedule.delete",
        "module": "attendance",
        "resource": "schedule",
        "action": "delete",
        "scope": "COMPANY",
        "description": "Delete working schedules.",
    },
    # Income & Expense (action-level)
    {
        "code": "income_expense.category.view",
        "module": "income_expense",
        "resource": "category",
        "action": "view",
        "scope": "COMPANY",
        "description": "View income/expense categories.",
    },
    {
        "code": "income_expense.category.create",
        "module": "income_expense",
        "resource": "category",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create income/expense categories.",
    },
    {
        "code": "income_expense.category.update",
        "module": "income_expense",
        "resource": "category",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update income/expense categories.",
    },
    {
        "code": "income_expense.category.delete",
        "module": "income_expense",
        "resource": "category",
        "action": "delete",
        "scope": "COMPANY",
        "description": "Delete income/expense categories.",
    },
    {
        "code": "income_expense.budget.view",
        "module": "income_expense",
        "resource": "budget",
        "action": "view",
        "scope": "COMPANY",
        "description": "View budget plans.",
    },
    {
        "code": "income_expense.budget.create",
        "module": "income_expense",
        "resource": "budget",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create budget plans.",
    },
    {
        "code": "income_expense.budget.update",
        "module": "income_expense",
        "resource": "budget",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update budget plans.",
    },
    {
        "code": "income_expense.budget.delete",
        "module": "income_expense",
        "resource": "budget",
        "action": "delete",
        "scope": "COMPANY",
        "description": "Delete budget plans.",
    },
    {
        "code": "income_expense.budget.activate",
        "module": "income_expense",
        "resource": "budget",
        "action": "activate",
        "scope": "COMPANY",
        "description": "Activate budget plans.",
    },
    {
        "code": "income_expense.expense.view",
        "module": "income_expense",
        "resource": "expense",
        "action": "view",
        "scope": "COMPANY",
        "description": "View expense claims.",
    },
    {
        "code": "income_expense.expense.create",
        "module": "income_expense",
        "resource": "expense",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create expense claims.",
    },
    {
        "code": "income_expense.expense.update",
        "module": "income_expense",
        "resource": "expense",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update expense claims.",
    },
    {
        "code": "income_expense.expense.delete",
        "module": "income_expense",
        "resource": "expense",
        "action": "delete",
        "scope": "COMPANY",
        "description": "Delete expense claims.",
    },
    {
        "code": "income_expense.expense.submit",
        "module": "income_expense",
        "resource": "expense",
        "action": "submit",
        "scope": "COMPANY",
        "description": "Submit expense claims.",
    },
    {
        "code": "income_expense.expense.approve",
        "module": "income_expense",
        "resource": "expense",
        "action": "approve",
        "scope": "COMPANY",
        "description": "Approve expense claims.",
    },
    {
        "code": "income_expense.expense.reject",
        "module": "income_expense",
        "resource": "expense",
        "action": "reject",
        "scope": "COMPANY",
        "description": "Reject expense claims.",
    },
    {
        "code": "income_expense.expense.cancel",
        "module": "income_expense",
        "resource": "expense",
        "action": "cancel",
        "scope": "COMPANY",
        "description": "Cancel expense claims.",
    },
    {
        "code": "income_expense.expense.mark_paid",
        "module": "income_expense",
        "resource": "expense",
        "action": "mark_paid",
        "scope": "COMPANY",
        "description": "Mark expenses as paid.",
    },
    {
        "code": "income_expense.income.view",
        "module": "income_expense",
        "resource": "income",
        "action": "view",
        "scope": "COMPANY",
        "description": "View income records.",
    },
    {
        "code": "income_expense.income.create",
        "module": "income_expense",
        "resource": "income",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create income records.",
    },
    {
        "code": "income_expense.income.update",
        "module": "income_expense",
        "resource": "income",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update income records.",
    },
    {
        "code": "income_expense.income.delete",
        "module": "income_expense",
        "resource": "income",
        "action": "delete",
        "scope": "COMPANY",
        "description": "Delete income records.",
    },
    {
        "code": "income_expense.income.submit",
        "module": "income_expense",
        "resource": "income",
        "action": "submit",
        "scope": "COMPANY",
        "description": "Submit income records.",
    },
    {
        "code": "income_expense.income.approve",
        "module": "income_expense",
        "resource": "income",
        "action": "approve",
        "scope": "COMPANY",
        "description": "Approve income records.",
    },
    {
        "code": "income_expense.income.reject",
        "module": "income_expense",
        "resource": "income",
        "action": "reject",
        "scope": "COMPANY",
        "description": "Reject income records.",
    },
    {
        "code": "income_expense.income.mark_received",
        "module": "income_expense",
        "resource": "income",
        "action": "mark_received",
        "scope": "COMPANY",
        "description": "Mark income as received.",
    },
    # Treasury (action-level)
    {
        "code": "treasury.account.view",
        "module": "treasury",
        "resource": "account",
        "action": "view",
        "scope": "COMPANY",
        "description": "View bank accounts.",
    },
    {
        "code": "treasury.account.create",
        "module": "treasury",
        "resource": "account",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create bank accounts.",
    },
    {
        "code": "treasury.account.update",
        "module": "treasury",
        "resource": "account",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update bank accounts.",
    },
    {
        "code": "treasury.account.delete",
        "module": "treasury",
        "resource": "account",
        "action": "delete",
        "scope": "COMPANY",
        "description": "Delete bank accounts.",
    },
    {
        "code": "treasury.account.withdraw",
        "module": "treasury",
        "resource": "account",
        "action": "withdraw",
        "scope": "COMPANY",
        "description": "Withdraw from bank accounts to cash desk.",
    },
    {
        "code": "treasury.cashdesk.view",
        "module": "treasury",
        "resource": "cashdesk",
        "action": "view",
        "scope": "COMPANY",
        "description": "View cash desks.",
    },
    {
        "code": "treasury.cashdesk.create",
        "module": "treasury",
        "resource": "cashdesk",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create cash desks.",
    },
    {
        "code": "treasury.cashdesk.update",
        "module": "treasury",
        "resource": "cashdesk",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update cash desks.",
    },
    {
        "code": "treasury.cashdesk.delete",
        "module": "treasury",
        "resource": "cashdesk",
        "action": "delete",
        "scope": "COMPANY",
        "description": "Delete cash desks.",
    },
    {
        "code": "treasury.cashdesk.open",
        "module": "treasury",
        "resource": "cashdesk",
        "action": "open",
        "scope": "COMPANY",
        "description": "Open cash desk sessions.",
    },
    {
        "code": "treasury.cashdesk.close",
        "module": "treasury",
        "resource": "cashdesk",
        "action": "close",
        "scope": "COMPANY",
        "description": "Close cash desk sessions.",
    },
    {
        "code": "treasury.cashdesk.cash_in",
        "module": "treasury",
        "resource": "cashdesk",
        "action": "cash_in",
        "scope": "COMPANY",
        "description": "Register cash in operations.",
    },
    {
        "code": "treasury.cashdesk.cash_out",
        "module": "treasury",
        "resource": "cashdesk",
        "action": "cash_out",
        "scope": "COMPANY",
        "description": "Register cash out operations.",
    },
    {
        "code": "treasury.cashdesk.transfer_to_bank",
        "module": "treasury",
        "resource": "cashdesk",
        "action": "transfer_to_bank",
        "scope": "COMPANY",
        "description": "Transfer cash desk funds to bank.",
    },
    {
        "code": "treasury.payment.view",
        "module": "treasury",
        "resource": "payment",
        "action": "view",
        "scope": "COMPANY",
        "description": "View payment batches and lines.",
    },
    {
        "code": "treasury.payment.create",
        "module": "treasury",
        "resource": "payment",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create payment batches.",
    },
    {
        "code": "treasury.payment.update",
        "module": "treasury",
        "resource": "payment",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update payment batches.",
    },
    {
        "code": "treasury.payment.delete",
        "module": "treasury",
        "resource": "payment",
        "action": "delete",
        "scope": "COMPANY",
        "description": "Delete payment batches.",
    },
    {
        "code": "treasury.payment.submit",
        "module": "treasury",
        "resource": "payment",
        "action": "submit",
        "scope": "COMPANY",
        "description": "Submit payment batches for approval.",
    },
    {
        "code": "treasury.payment.approve",
        "module": "treasury",
        "resource": "payment",
        "action": "approve",
        "scope": "COMPANY",
        "description": "Approve payment batches.",
    },
    {
        "code": "treasury.payment.execute",
        "module": "treasury",
        "resource": "payment",
        "action": "execute",
        "scope": "COMPANY",
        "description": "Execute payments.",
    },
    {
        "code": "treasury.payment.cancel",
        "module": "treasury",
        "resource": "payment",
        "action": "cancel",
        "scope": "COMPANY",
        "description": "Cancel payments.",
    },
    {
        "code": "treasury.payment.mark_paid",
        "module": "treasury",
        "resource": "payment",
        "action": "mark_paid",
        "scope": "COMPANY",
        "description": "Mark payments as paid.",
    },
    {
        "code": "treasury.payment.fail",
        "module": "treasury",
        "resource": "payment",
        "action": "fail",
        "scope": "COMPANY",
        "description": "Mark payments as failed.",
    },
    {
        "code": "treasury.statement.view",
        "module": "treasury",
        "resource": "statement",
        "action": "view",
        "scope": "COMPANY",
        "description": "View bank statements.",
    },
    {
        "code": "treasury.statement.create",
        "module": "treasury",
        "resource": "statement",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create bank statements.",
    },
    {
        "code": "treasury.statement.update",
        "module": "treasury",
        "resource": "statement",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update bank statements.",
    },
    {
        "code": "treasury.statement.delete",
        "module": "treasury",
        "resource": "statement",
        "action": "delete",
        "scope": "COMPANY",
        "description": "Delete bank statements.",
    },
    {
        "code": "treasury.statement.import",
        "module": "treasury",
        "resource": "statement",
        "action": "import",
        "scope": "COMPANY",
        "description": "Import bank statements.",
    },
    # Fleets (action-level)
    {
        "code": "fleets.configuration.view",
        "module": "fleets",
        "resource": "configuration",
        "action": "view",
        "scope": "COMPANY",
        "description": "View fleet configuration.",
    },
    {
        "code": "fleets.configuration.create",
        "module": "fleets",
        "resource": "configuration",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create fleet configuration items.",
    },
    {
        "code": "fleets.configuration.update",
        "module": "fleets",
        "resource": "configuration",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update fleet configuration items.",
    },
    {
        "code": "fleets.configuration.delete",
        "module": "fleets",
        "resource": "configuration",
        "action": "delete",
        "scope": "COMPANY",
        "description": "Delete fleet configuration items.",
    },
    {
        "code": "fleets.vehicle.view",
        "module": "fleets",
        "resource": "vehicle",
        "action": "view",
        "scope": "COMPANY",
        "description": "View fleet vehicles.",
    },
    {
        "code": "fleets.vehicle.create",
        "module": "fleets",
        "resource": "vehicle",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create fleet vehicles.",
    },
    {
        "code": "fleets.vehicle.update",
        "module": "fleets",
        "resource": "vehicle",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update fleet vehicles.",
    },
    {
        "code": "fleets.vehicle.delete",
        "module": "fleets",
        "resource": "vehicle",
        "action": "delete",
        "scope": "COMPANY",
        "description": "Delete fleet vehicles.",
    },
    {
        "code": "fleets.assignment.view",
        "module": "fleets",
        "resource": "assignment",
        "action": "view",
        "scope": "COMPANY",
        "description": "View driver assignments.",
    },
    {
        "code": "fleets.assignment.create",
        "module": "fleets",
        "resource": "assignment",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create driver assignments.",
    },
    {
        "code": "fleets.assignment.update",
        "module": "fleets",
        "resource": "assignment",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update driver assignments.",
    },
    {
        "code": "fleets.assignment.delete",
        "module": "fleets",
        "resource": "assignment",
        "action": "delete",
        "scope": "COMPANY",
        "description": "Delete driver assignments.",
    },
    {
        "code": "fleets.contract.view",
        "module": "fleets",
        "resource": "contract",
        "action": "view",
        "scope": "COMPANY",
        "description": "View vehicle contracts.",
    },
    {
        "code": "fleets.contract.create",
        "module": "fleets",
        "resource": "contract",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create vehicle contracts.",
    },
    {
        "code": "fleets.contract.update",
        "module": "fleets",
        "resource": "contract",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update vehicle contracts.",
    },
    {
        "code": "fleets.contract.delete",
        "module": "fleets",
        "resource": "contract",
        "action": "delete",
        "scope": "COMPANY",
        "description": "Delete vehicle contracts.",
    },
    {
        "code": "fleets.service.view",
        "module": "fleets",
        "resource": "service",
        "action": "view",
        "scope": "COMPANY",
        "description": "View service records.",
    },
    {
        "code": "fleets.service.create",
        "module": "fleets",
        "resource": "service",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create service records.",
    },
    {
        "code": "fleets.service.update",
        "module": "fleets",
        "resource": "service",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update service records.",
    },
    {
        "code": "fleets.service.delete",
        "module": "fleets",
        "resource": "service",
        "action": "delete",
        "scope": "COMPANY",
        "description": "Delete service records.",
    },
    {
        "code": "fleets.accident.view",
        "module": "fleets",
        "resource": "accident",
        "action": "view",
        "scope": "COMPANY",
        "description": "View accident events.",
    },
    {
        "code": "fleets.accident.create",
        "module": "fleets",
        "resource": "accident",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create accident events.",
    },
    {
        "code": "fleets.accident.update",
        "module": "fleets",
        "resource": "accident",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update accident events.",
    },
    {
        "code": "fleets.accident.delete",
        "module": "fleets",
        "resource": "accident",
        "action": "delete",
        "scope": "COMPANY",
        "description": "Delete accident events.",
    },
    # Frontdesk (action-level)
    {
        "code": "frontdesk.station.view",
        "module": "frontdesk",
        "resource": "station",
        "action": "view",
        "scope": "COMPANY",
        "description": "View front desk stations.",
    },
    {
        "code": "frontdesk.station.create",
        "module": "frontdesk",
        "resource": "station",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create front desk stations.",
    },
    {
        "code": "frontdesk.station.update",
        "module": "frontdesk",
        "resource": "station",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update front desk stations.",
    },
    {
        "code": "frontdesk.station.delete",
        "module": "frontdesk",
        "resource": "station",
        "action": "delete",
        "scope": "COMPANY",
        "description": "Delete front desk stations.",
    },
    {
        "code": "frontdesk.responsible.view",
        "module": "frontdesk",
        "resource": "responsible",
        "action": "view",
        "scope": "COMPANY",
        "description": "View station responsibles.",
    },
    {
        "code": "frontdesk.responsible.create",
        "module": "frontdesk",
        "resource": "responsible",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create station responsibles.",
    },
    {
        "code": "frontdesk.responsible.update",
        "module": "frontdesk",
        "resource": "responsible",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update station responsibles.",
    },
    {
        "code": "frontdesk.responsible.delete",
        "module": "frontdesk",
        "resource": "responsible",
        "action": "delete",
        "scope": "COMPANY",
        "description": "Delete station responsibles.",
    },
    {
        "code": "frontdesk.visitor.view",
        "module": "frontdesk",
        "resource": "visitor",
        "action": "view",
        "scope": "COMPANY",
        "description": "View visitors.",
    },
    {
        "code": "frontdesk.visitor.create",
        "module": "frontdesk",
        "resource": "visitor",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create visitors.",
    },
    {
        "code": "frontdesk.visitor.update",
        "module": "frontdesk",
        "resource": "visitor",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update visitors.",
    },
    {
        "code": "frontdesk.visitor.delete",
        "module": "frontdesk",
        "resource": "visitor",
        "action": "delete",
        "scope": "COMPANY",
        "description": "Delete visitors.",
    },
    {
        "code": "frontdesk.visit.view",
        "module": "frontdesk",
        "resource": "visit",
        "action": "view",
        "scope": "COMPANY",
        "description": "View visits.",
    },
    {
        "code": "frontdesk.visit.create",
        "module": "frontdesk",
        "resource": "visit",
        "action": "create",
        "scope": "COMPANY",
        "description": "Create visits.",
    },
    {
        "code": "frontdesk.visit.update",
        "module": "frontdesk",
        "resource": "visit",
        "action": "update",
        "scope": "COMPANY",
        "description": "Update visits.",
    },
    {
        "code": "frontdesk.visit.delete",
        "module": "frontdesk",
        "resource": "visit",
        "action": "delete",
        "scope": "COMPANY",
        "description": "Delete visits.",
    },
    {
        "code": "frontdesk.visit.check_in",
        "module": "frontdesk",
        "resource": "visit",
        "action": "check_in",
        "scope": "COMPANY",
        "description": "Check in visitors.",
    },
    {
        "code": "frontdesk.visit.check_out",
        "module": "frontdesk",
        "resource": "visit",
        "action": "check_out",
        "scope": "COMPANY",
        "description": "Check out visitors.",
    },
    {
        "code": "frontdesk.visit.cancel",
        "module": "frontdesk",
        "resource": "visit",
        "action": "cancel",
        "scope": "COMPANY",
        "description": "Cancel visits.",
    },
]


def ensure_default_permissions():
    """Create any missing permissions from the default catalog."""
    created = 0
    for entry in DEFAULT_PERMISSIONS:
        code = entry["code"]
        _, was_created = Permission.objects.get_or_create(code=code, defaults=entry)
        if was_created:
            created += 1
    return created

