# Generated by Django 5.2.8 on 2025-12-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROBATION', 'Probation'), ('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated'), ('RESIGNED', 'Resigned'), ('RETIRED', 'Retired')], default='PENDING', max_length=20),
        ),
    ]
