# Generated by Django 5.2.8 on 2025-12-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Company-assigned employee ID (auto-generated if not provided)', max_length=50),
        ),
    ]
