# Generated by Django 5.2.8 on 2025-12-15 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this department belongs to (optional for company-wide departments)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='employees.branch'),
        ),
    ]
