# Generated by Django 5.2.8 on 2025-12-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_employment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeconfiguration',
            name='last_employee_number',
            field=models.IntegerField(default=0, help_text='Last used employee number (auto-incremented)'),
        ),
    ]
