# Generated by Django 5.2.8 on 2026-02-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employeeconfiguration_require_employee_consent_cross_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_multi_branch',
            field=models.BooleanField(default=False, help_text='Employee can be assigned to multiple branches'),
        ),
        migrations.AddField(
            model_name='employee',
            name='secondary_branches',
            field=models.ManyToManyField(blank=True, help_text='Additional branch assignments for multi-branch employees', related_name='secondary_employees', to='employees.branch'),
        ),
    ]
