# Generated by Django 5.2.8 on 2026-02-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_is_multi_branch_employee_secondary_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeconfiguration',
            name='multi_branch_enabled',
            field=models.BooleanField(default=False, help_text='Enable branch assignment fields across employee management workflows'),
        ),
    ]
