# Generated by Django 5.2.9 on 2026-02-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_consent_scopes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='document_type',
            field=models.CharField(choices=[('RESUME', 'Resume/CV'), ('ID_COPY', 'ID Copy'), ('PASSPORT_COPY', 'Passport Copy'), ('BIRTH_CERTIFICATE', 'Birth Certificate'), ('CERTIFICATE', 'Certificate/Diploma'), ('EMPLOYMENT_CERTIFICATE', 'Employment Certificate'), ('CONTRACT', 'Employment Contract'), ('OFFER_LETTER', 'Offer Letter'), ('TERMINATION_LETTER', 'Termination Letter'), ('RECOMMENDATION', 'Recommendation Letter'), ('MEDICAL', 'Medical Certificate'), ('POLICE_CLEARANCE', 'Police Clearance'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
