# Generated by Codex on 2026-01-16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0007_alter_employeedocument_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="badge_id",
            field=models.CharField(blank=True, db_index=True, help_text="Badge/RFID identifier", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="pin_code_hash",
            field=models.CharField(blank=True, help_text="Hashed kiosk PIN", max_length=128, null=True),
        ),
    ]
