# Generated by Django 5.2.9 on 2026-01-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_add_badge_and_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pin_hash',
            field=models.CharField(blank=True, help_text='Normalized hashed kiosk PIN (preferred)', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='rfid_tag_id',
            field=models.CharField(blank=True, db_index=True, help_text='RFID tag identifier', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='user_account_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Optional link to the portal user account (mirrors user_id where applicable)', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='working_schedule_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Attendance working schedule identifier (from attendance_working_schedules)', null=True),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('badge_id__isnull', False), models.Q(('badge_id', ''), _negated=True)), fields=('badge_id',), name='uniq_employee_badge_id'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('rfid_tag_id__isnull', False), models.Q(('rfid_tag_id', ''), _negated=True)), fields=('rfid_tag_id',), name='uniq_employee_rfid_tag_id'),
        ),
    ]
