# Generated by Django 5.2.9 on 2026-02-02 00:00

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RecruitmentSettings",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("employer_id", models.IntegerField(db_index=True, help_text="Employer ID from main database")),
                (
                    "tenant_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Alias for employer_id to simplify tenant-aware queries",
                        null=True,
                    ),
                ),
                ("schema_version", models.IntegerField(default=1)),
                (
                    "job_publish_scope",
                    models.CharField(
                        choices=[
                            ("INTERNAL_ONLY", "Internal only"),
                            ("PUBLIC_ONLY", "Public only"),
                            ("BOTH", "Internal + Public"),
                        ],
                        default="INTERNAL_ONLY",
                        max_length=20,
                    ),
                ),
                ("public_applications_enabled", models.BooleanField(default=False)),
                ("internal_applications_enabled", models.BooleanField(default=True)),
                ("public_apply_requires_login", models.BooleanField(default=False)),
                ("internal_apply_requires_login", models.BooleanField(default=True)),
                ("application_fields", models.JSONField(blank=True, default=list)),
                ("custom_questions", models.JSONField(blank=True, default=list)),
                ("email_automation_enabled", models.BooleanField(default=True)),
                ("default_ack_email_subject", models.CharField(blank=True, max_length=200)),
                ("default_ack_email_body", models.TextField(blank=True)),
                ("cv_allowed_extensions", models.JSONField(blank=True, default=list)),
                ("cv_max_file_size_mb", models.IntegerField(default=10)),
                ("public_apply_rate_limit_requests", models.IntegerField(default=20)),
                ("public_apply_rate_limit_window_seconds", models.IntegerField(default=3600)),
                ("public_apply_captcha_enabled", models.BooleanField(default=False)),
                ("public_apply_spam_check_enabled", models.BooleanField(default=True)),
                ("public_apply_honeypot_enabled", models.BooleanField(default=True)),
                ("duplicate_application_window_days", models.IntegerField(default=30)),
                (
                    "duplicate_application_action",
                    models.CharField(
                        choices=[("BLOCK", "Block"), ("WARN", "Warn"), ("ALLOW", "Allow")],
                        default="BLOCK",
                        max_length=10,
                    ),
                ),
                ("integration_interview_scheduling_enabled", models.BooleanField(default=False)),
                ("integration_offers_esign_enabled", models.BooleanField(default=False)),
                ("integration_resume_ocr_enabled", models.BooleanField(default=False)),
                ("integration_job_board_ingest_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "recruitment_settings",
                "verbose_name": "Recruitment Settings",
                "verbose_name_plural": "Recruitment Settings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecruitmentStage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("employer_id", models.IntegerField(db_index=True)),
                ("tenant_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.CharField(db_index=True, max_length=150)),
                ("sequence", models.IntegerField(default=1)),
                (
                    "scope",
                    models.CharField(
                        choices=[("GLOBAL", "Global"), ("JOB", "Job-specific")],
                        default="GLOBAL",
                        max_length=10,
                    ),
                ),
                ("job_id", models.CharField(blank=True, max_length=64, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("auto_email_enabled", models.BooleanField(default=False)),
                ("auto_email_subject", models.CharField(blank=True, max_length=200, null=True)),
                ("auto_email_body", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="recruitment.recruitmentsettings",
                    ),
                ),
            ],
            options={
                "db_table": "recruitment_stages",
                "ordering": ["sequence", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="recruitmentstage",
            index=models.Index(fields=["employer_id", "sequence"], name="recruitment_employer_seq_idx"),
        ),
        migrations.AddIndex(
            model_name="recruitmentstage",
            index=models.Index(fields=["employer_id", "scope"], name="recruitment_employer_scope_idx"),
        ),
        migrations.AddIndex(
            model_name="recruitmentstage",
            index=models.Index(fields=["job_id"], name="recruitment_job_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="recruitmentsettings",
            unique_together={("employer_id",)},
        ),
        migrations.AlterUniqueTogether(
            name="recruitmentstage",
            unique_together={("employer_id", "slug")},
        ),
    ]
