# Generated by Django 5.2.9 on 2026-02-02 00:00

import uuid
import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
        ("recruitment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruitmentstage",
            name="is_folded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recruitmentstage",
            name="is_hired_stage",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recruitmentstage",
            name="is_refused_stage",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="JobPosition",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("employer_id", models.IntegerField(db_index=True)),
                ("tenant_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("employment_type", models.CharField(blank=True, max_length=50, null=True)),
                ("is_remote", models.BooleanField(default=False)),
                (
                    "publish_scope",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("INTERNAL_ONLY", "Internal only"),
                            ("PUBLIC_ONLY", "Public only"),
                            ("BOTH", "Internal + Public"),
                        ],
                        help_text="Override publish scope for this job.",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("OPEN", "Open"), ("CLOSED", "Closed"), ("ARCHIVED", "Archived")], default="DRAFT", max_length=20)),
                ("created_by", models.IntegerField(db_index=True, help_text="User ID from main DB")),
                ("updated_by", models.IntegerField(db_index=True, help_text="User ID from main DB")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recruitment_jobs",
                        to="employees.branch",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recruitment_jobs",
                        to="employees.department",
                    ),
                ),
            ],
            options={
                "db_table": "recruitment_job_positions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecruitmentRefuseReason",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("employer_id", models.IntegerField(db_index=True)),
                ("tenant_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "recruitment_refuse_reasons",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RecruitmentApplicant",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("employer_id", models.IntegerField(db_index=True)),
                ("tenant_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("linkedin_url", models.CharField(blank=True, max_length=255, null=True)),
                ("intro", models.TextField(blank=True, null=True)),
                ("status", models.CharField(choices=[("NEW", "New"), ("IN_PROGRESS", "In Progress"), ("BLOCKED", "Blocked"), ("HIRED", "Hired"), ("REFUSED", "Refused")], db_index=True, default="NEW", max_length=20)),
                ("rating", models.IntegerField(default=0)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("source", models.CharField(blank=True, max_length=100, null=True)),
                ("medium", models.CharField(blank=True, max_length=100, null=True)),
                ("referral", models.CharField(blank=True, max_length=100, null=True)),
                ("answers", models.JSONField(blank=True, default=dict)),
                ("is_internal_applicant", models.BooleanField(default=False)),
                ("user_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("refuse_note", models.TextField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity_at", models.DateTimeField(default=timezone.now)),
                ("hired_at", models.DateTimeField(blank=True, null=True)),
                ("refused_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recruitment_applications",
                        to="employees.employee",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="applicants", to="recruitment.jobposition"),
                ),
                (
                    "refuse_reason",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refused_applicants",
                        to="recruitment.recruitmentrefusereason",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applicants",
                        to="recruitment.recruitmentstage",
                    ),
                ),
            ],
            options={
                "db_table": "recruitment_applicants",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecruitmentApplicantStageHistory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("action", models.CharField(choices=[("APPLY", "Apply"), ("MOVE_STAGE", "Move stage"), ("REFUSE", "Refuse"), ("HIRED", "Hired")], default="MOVE_STAGE", max_length=20)),
                ("changed_by_user_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applicant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="stage_history", to="recruitment.recruitmentapplicant"),
                ),
                (
                    "from_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stage_history_from",
                        to="recruitment.recruitmentstage",
                    ),
                ),
                (
                    "to_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stage_history_to",
                        to="recruitment.recruitmentstage",
                    ),
                ),
            ],
            options={
                "db_table": "recruitment_applicant_stage_history",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="RecruitmentEmailTemplate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("employer_id", models.IntegerField(db_index=True)),
                ("tenant_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("code", models.CharField(choices=[("APPLICATION_ACK", "Application acknowledgement"), ("STAGE_ENTER", "Stage entry"), ("REFUSAL", "Refusal")], max_length=50)),
                ("job_id", models.CharField(blank=True, max_length=64, null=True)),
                ("subject", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_templates",
                        to="recruitment.recruitmentstage",
                    ),
                ),
            ],
            options={
                "db_table": "recruitment_email_templates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecruitmentEmailLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("employer_id", models.IntegerField(db_index=True)),
                ("tenant_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("to_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("status", models.CharField(choices=[("SENT", "Sent"), ("FAILED", "Failed")], default="SENT", max_length=20)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="recruitment.recruitmentapplicant",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="recruitment.jobposition",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to="recruitment.recruitmentemailtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "recruitment_email_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecruitmentAttachment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("employer_id", models.IntegerField(db_index=True)),
                ("tenant_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("file", models.FileField(upload_to="recruitment_attachments/")),
                ("file_size", models.IntegerField(help_text="File size in bytes")),
                ("content_type", models.CharField(blank=True, max_length=100, null=True)),
                ("original_name", models.CharField(blank=True, max_length=255, null=True)),
                ("purpose", models.CharField(choices=[("CV", "CV"), ("COVER_LETTER", "Cover letter"), ("OTHER", "Other")], default="CV", max_length=20)),
                ("virus_scan_status", models.CharField(choices=[("PENDING", "Pending"), ("CLEAN", "Clean"), ("INFECTED", "Infected"), ("SKIPPED", "Skipped")], default="PENDING", max_length=20)),
                ("uploaded_by_user_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applicant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="recruitment.recruitmentapplicant"),
                ),
            ],
            options={
                "db_table": "recruitment_attachments",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="RecruitmentInterviewEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("employer_id", models.IntegerField(db_index=True)),
                ("tenant_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("scheduled_at", models.DateTimeField()),
                ("duration_minutes", models.IntegerField(default=30)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("meeting_link", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(choices=[("SCHEDULED", "Scheduled"), ("COMPLETED", "Completed"), ("CANCELLED", "Cancelled")], default="SCHEDULED", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applicant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="interviews", to="recruitment.recruitmentapplicant"),
                ),
            ],
            options={
                "db_table": "recruitment_interview_events",
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="RecruitmentOffer",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("employer_id", models.IntegerField(db_index=True)),
                ("tenant_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("SENT", "Sent"), ("ACCEPTED", "Accepted"), ("DECLINED", "Declined")], default="DRAFT", max_length=20)),
                ("notes", models.TextField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applicant",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="offers", to="recruitment.recruitmentapplicant"),
                ),
            ],
            options={
                "db_table": "recruitment_offers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="jobposition",
            index=models.Index(fields=["employer_id", "status"], name="recruitment_job_employer_status_idx"),
        ),
        migrations.AddIndex(
            model_name="jobposition",
            index=models.Index(fields=["employer_id", "is_published"], name="recruitment_job_employer_published_idx"),
        ),
        migrations.AddIndex(
            model_name="jobposition",
            index=models.Index(fields=["employer_id", "created_at"], name="recruitment_job_employer_created_idx"),
        ),
        migrations.AddIndex(
            model_name="recruitmentapplicant",
            index=models.Index(fields=["employer_id", "job"], name="recruitment_applicant_employer_job_idx"),
        ),
        migrations.AddIndex(
            model_name="recruitmentapplicant",
            index=models.Index(fields=["employer_id", "status"], name="recruitment_applicant_employer_status_idx"),
        ),
        migrations.AddIndex(
            model_name="recruitmentapplicant",
            index=models.Index(fields=["employer_id", "email"], name="recruitment_applicant_employer_email_idx"),
        ),
        migrations.AddIndex(
            model_name="recruitmentapplicant",
            index=models.Index(fields=["job", "stage"], name="recruitment_applicant_job_stage_idx"),
        ),
        migrations.AddIndex(
            model_name="recruitmentapplicantstagehistory",
            index=models.Index(fields=["applicant", "changed_at"], name="recruitment_stage_history_applicant_idx"),
        ),
        migrations.AddIndex(
            model_name="recruitmentapplicantstagehistory",
            index=models.Index(fields=["to_stage", "changed_at"], name="recruitment_stage_history_stage_idx"),
        ),
        migrations.AddIndex(
            model_name="recruitmentrefusereason",
            index=models.Index(fields=["employer_id", "is_active"], name="recruitment_refuse_reason_active_idx"),
        ),
        migrations.AddIndex(
            model_name="recruitmentemailtemplate",
            index=models.Index(fields=["employer_id", "code"], name="recruitment_email_template_code_idx"),
        ),
        migrations.AddIndex(
            model_name="recruitmentemailtemplate",
            index=models.Index(fields=["stage", "code"], name="recruitment_email_template_stage_idx"),
        ),
        migrations.AddIndex(
            model_name="recruitmentemaillog",
            index=models.Index(fields=["employer_id", "created_at"], name="recruitment_email_log_created_idx"),
        ),
        migrations.AddIndex(
            model_name="recruitmentattachment",
            index=models.Index(fields=["employer_id", "purpose"], name="recruitment_attachment_purpose_idx"),
        ),
        migrations.AddIndex(
            model_name="recruitmentinterviewevent",
            index=models.Index(fields=["employer_id", "scheduled_at"], name="recruitment_interview_scheduled_idx"),
        ),
        migrations.AddIndex(
            model_name="recruitmentoffer",
            index=models.Index(fields=["employer_id", "status"], name="recruitment_offer_status_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="jobposition",
            unique_together={("employer_id", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="recruitmentrefusereason",
            unique_together={("employer_id", "code")},
        ),
    ]
