# Generated by Django 5.2.11 on 2026-02-12 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_job_position_details'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='jobposition',
            new_name='recruitment_employe_b2ecd3_idx',
            old_name='recruitment_job_employer_status_idx',
        ),
        migrations.RenameIndex(
            model_name='jobposition',
            new_name='recruitment_employe_c89114_idx',
            old_name='recruitment_job_employer_published_idx',
        ),
        migrations.RenameIndex(
            model_name='jobposition',
            new_name='recruitment_employe_5738d9_idx',
            old_name='recruitment_job_employer_created_idx',
        ),
        migrations.RenameIndex(
            model_name='recruitmentapplicant',
            new_name='recruitment_employe_f42cb3_idx',
            old_name='recruitment_applicant_employer_job_idx',
        ),
        migrations.RenameIndex(
            model_name='recruitmentapplicant',
            new_name='recruitment_employe_b88762_idx',
            old_name='recruitment_applicant_employer_status_idx',
        ),
        migrations.RenameIndex(
            model_name='recruitmentapplicant',
            new_name='recruitment_employe_5570fd_idx',
            old_name='recruitment_applicant_employer_email_idx',
        ),
        migrations.RenameIndex(
            model_name='recruitmentapplicant',
            new_name='recruitment_job_id_d66e9e_idx',
            old_name='recruitment_applicant_job_stage_idx',
        ),
        migrations.RenameIndex(
            model_name='recruitmentapplicantstagehistory',
            new_name='recruitment_applica_0a3fa6_idx',
            old_name='recruitment_stage_history_applicant_idx',
        ),
        migrations.RenameIndex(
            model_name='recruitmentapplicantstagehistory',
            new_name='recruitment_to_stag_02bd1e_idx',
            old_name='recruitment_stage_history_stage_idx',
        ),
        migrations.RenameIndex(
            model_name='recruitmentattachment',
            new_name='recruitment_employe_1f3b94_idx',
            old_name='recruitment_attachment_purpose_idx',
        ),
        migrations.RenameIndex(
            model_name='recruitmentemaillog',
            new_name='recruitment_employe_bbd8ea_idx',
            old_name='recruitment_email_log_created_idx',
        ),
        migrations.RenameIndex(
            model_name='recruitmentemailtemplate',
            new_name='recruitment_employe_ccbf50_idx',
            old_name='recruitment_email_template_code_idx',
        ),
        migrations.RenameIndex(
            model_name='recruitmentemailtemplate',
            new_name='recruitment_stage_i_9fdfca_idx',
            old_name='recruitment_email_template_stage_idx',
        ),
        migrations.RenameIndex(
            model_name='recruitmentinterviewevent',
            new_name='recruitment_employe_cb5f43_idx',
            old_name='recruitment_interview_scheduled_idx',
        ),
        migrations.RenameIndex(
            model_name='recruitmentoffer',
            new_name='recruitment_employe_a517f2_idx',
            old_name='recruitment_offer_status_idx',
        ),
        migrations.RenameIndex(
            model_name='recruitmentrefusereason',
            new_name='recruitment_employe_3e6611_idx',
            old_name='recruitment_refuse_reason_active_idx',
        ),
        migrations.RenameIndex(
            model_name='recruitmentstage',
            new_name='recruitment_employe_e8c9d5_idx',
            old_name='recruitment_employer_seq_idx',
        ),
        migrations.RenameIndex(
            model_name='recruitmentstage',
            new_name='recruitment_employe_e6a707_idx',
            old_name='recruitment_employer_scope_idx',
        ),
        migrations.RenameIndex(
            model_name='recruitmentstage',
            new_name='recruitment_job_id_0ec24c_idx',
            old_name='recruitment_job_idx',
        ),
    ]

# Generated by Django 5.2.9 on 2026-02-14 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_job_position_details'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='jobposition',
            new_name='recruitment_employe_b2ecd3_idx',
            old_name='recruitment_job_employer_status_idx',
        ),
        migrations.RenameIndex(
            model_name='jobposition',
            new_name='recruitment_employe_c89114_idx',
            old_name='recruitment_job_employer_published_idx',
        ),
        migrations.RenameIndex(
            model_name='jobposition',
            new_name='recruitment_employe_5738d9_idx',
            old_name='recruitment_job_employer_created_idx',
        ),
        migrations.RenameIndex(
            model_name='recruitmentapplicant',
            new_name='recruitment_employe_f42cb3_idx',
            old_name='recruitment_applicant_employer_job_idx',
        ),
        migrations.RenameIndex(
            model_name='recruitmentapplicant',
            new_name='recruitment_employe_b88762_idx',
            old_name='recruitment_applicant_employer_status_idx',
        ),
        migrations.RenameIndex(
            model_name='recruitmentapplicant',
            new_name='recruitment_employe_5570fd_idx',
            old_name='recruitment_applicant_employer_email_idx',
        ),
        migrations.RenameIndex(
            model_name='recruitmentapplicant',
            new_name='recruitment_job_id_d66e9e_idx',
            old_name='recruitment_applicant_job_stage_idx',
        ),
        migrations.RenameIndex(
            model_name='recruitmentapplicantstagehistory',
            new_name='recruitment_applica_0a3fa6_idx',
            old_name='recruitment_stage_history_applicant_idx',
        ),
        migrations.RenameIndex(
            model_name='recruitmentapplicantstagehistory',
            new_name='recruitment_to_stag_02bd1e_idx',
            old_name='recruitment_stage_history_stage_idx',
        ),
        migrations.RenameIndex(
            model_name='recruitmentattachment',
            new_name='recruitment_employe_1f3b94_idx',
            old_name='recruitment_attachment_purpose_idx',
        ),
        migrations.RenameIndex(
            model_name='recruitmentemaillog',
            new_name='recruitment_employe_bbd8ea_idx',
            old_name='recruitment_email_log_created_idx',
        ),
        migrations.RenameIndex(
            model_name='recruitmentemailtemplate',
            new_name='recruitment_employe_ccbf50_idx',
            old_name='recruitment_email_template_code_idx',
        ),
        migrations.RenameIndex(
            model_name='recruitmentemailtemplate',
            new_name='recruitment_stage_i_9fdfca_idx',
            old_name='recruitment_email_template_stage_idx',
        ),
        migrations.RenameIndex(
            model_name='recruitmentinterviewevent',
            new_name='recruitment_employe_cb5f43_idx',
            old_name='recruitment_interview_scheduled_idx',
        ),
        migrations.RenameIndex(
            model_name='recruitmentoffer',
            new_name='recruitment_employe_a517f2_idx',
            old_name='recruitment_offer_status_idx',
        ),
        migrations.RenameIndex(
            model_name='recruitmentrefusereason',
            new_name='recruitment_employe_3e6611_idx',
            old_name='recruitment_refuse_reason_active_idx',
        ),
        migrations.RenameIndex(
            model_name='recruitmentstage',
            new_name='recruitment_employe_e8c9d5_idx',
            old_name='recruitment_employer_seq_idx',
        ),
        migrations.RenameIndex(
            model_name='recruitmentstage',
            new_name='recruitment_employe_e6a707_idx',
            old_name='recruitment_employer_scope_idx',
        ),
        migrations.RenameIndex(
            model_name='recruitmentstage',
            new_name='recruitment_job_id_0ec24c_idx',
            old_name='recruitment_job_idx',
        ),
    ]
