# Generated by Django 5.2.8 on 2026-01-01 18:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0006_configuration_enhancements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer_id', models.IntegerField(db_index=True, help_text='ID of the employer (from main database)')),
                ('contract_id', models.CharField(help_text='Unique contract identifier (auto-generated or manual)', max_length=50, unique=True)),
                ('institution', models.CharField(help_text='Institution or company name', max_length=255)),
                ('contract_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('FIXED_TERM', 'Fixed-Term'), ('INTERNSHIP', 'Internship'), ('CONSULTANT', 'Consultant'), ('PART_TIME', 'Part-Time')], help_text='Type of employment contract', max_length=20)),
                ('start_date', models.DateField(help_text='Contract start date')),
                ('end_date', models.DateField(blank=True, help_text='Contract end date (nullable for permanent contracts)', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_SIGNATURE', 'Pending Signature'), ('SIGNED', 'Signed'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Current status of the contract', max_length=20)),
                ('base_salary', models.DecimalField(decimal_places=2, help_text='Base salary amount', max_digits=12)),
                ('currency', models.CharField(default='XAF', help_text='Currency code (e.g., XAF, USD, EUR)', max_length=3)),
                ('pay_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('BI_WEEKLY', 'Bi-Weekly'), ('WEEKLY', 'Weekly'), ('DAILY', 'Daily')], default='MONTHLY', help_text='Payment frequency', max_length=20)),
                ('created_by', models.IntegerField(db_index=True, help_text='ID of the user who created this contract (from main database)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch where employee works', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='employees.branch')),
                ('department', models.ForeignKey(blank=True, help_text='Department where employee works', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='employees.department')),
                ('employee', models.ForeignKey(help_text='Employee this contract belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'db_table': 'contracts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employer_id', 'status'], name='contracts_employe_e50117_idx'), models.Index(fields=['employee', 'status'], name='contracts_employe_a560a5_idx'), models.Index(fields=['start_date', 'end_date'], name='contracts_start_d_f0a101_idx')],
                'unique_together': {('employer_id', 'contract_id')},
            },
        ),
    ]
