# Generated by Django 5.2.8 on 2026-01-01 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the allowance/deduction', max_length=255)),
                ('type', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage of Base Salary')], default='FIXED', help_text='Type of calculation', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount value (currency or percentage)', max_digits=12)),
                ('taxable', models.BooleanField(default=True, help_text='Is this component taxable?')),
                ('cnps_base', models.BooleanField(default=True, help_text='Is this component part of CNPS base?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(help_text='Contract this component belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Allowance',
                'verbose_name_plural': 'Allowances',
                'db_table': 'contract_allowances',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the allowance/deduction', max_length=255)),
                ('type', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage of Base Salary')], default='FIXED', help_text='Type of calculation', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount value (currency or percentage)', max_digits=12)),
                ('taxable', models.BooleanField(default=True, help_text='Is this component taxable?')),
                ('cnps_base', models.BooleanField(default=True, help_text='Is this component part of CNPS base?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(help_text='Contract this component belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Deduction',
                'verbose_name_plural': 'Deductions',
                'db_table': 'contract_deductions',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
