# Generated by Django 5.2.8 on 2026-01-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contractaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_id', models.IntegerField(db_index=True, help_text='ID of the employer (from main database)')),
                ('name', models.CharField(help_text='Name of the template', max_length=255)),
                ('contract_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('FIXED_TERM', 'Fixed-Term'), ('INTERNSHIP', 'Internship'), ('CONSULTANT', 'Consultant'), ('PART_TIME', 'Part-Time')], help_text='Type of contract this template applies to', max_length=20)),
                ('file', models.FileField(help_text='Template file (DOCX, PDF, etc.)', upload_to='contract_templates/')),
                ('is_default', models.BooleanField(default=False, help_text='Use as default template for this contract type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contract Template',
                'verbose_name_plural': 'Contract Templates',
                'db_table': 'contract_templates',
                'ordering': ['-created_at'],
            },
        ),
    ]
