# Generated by Django 5.2.8 on 2026-01-01 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contracttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name of the document', max_length=255)),
                ('file', models.FileField(help_text='The generated document file', upload_to='contract_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(help_text='Contract this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contracts.contract')),
                ('generated_from', models.ForeignKey(blank=True, help_text='Template used to generate this document', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.contracttemplate')),
            ],
            options={
                'verbose_name': 'Contract Document',
                'verbose_name_plural': 'Contract Documents',
                'db_table': 'contract_documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
