# Generated by Django 5.2.11 on 2026-02-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_allowance_advantage_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='final_pay_flag',
            field=models.BooleanField(default=False, help_text='Flag to trigger final compensation calculation'),
        ),
        migrations.AlterField(
            model_name='contractconfiguration',
            name='payroll_configuration',
            field=models.JSONField(blank=True, default=dict, help_text='Compensation inputs (tax profile, CNPS, probation, proration)'),
        ),
    ]
