# Generated by Django 5.2.8 on 2026-01-01 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_contractdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_name', models.CharField(help_text='Typed name of the signer', max_length=255)),
                ('role', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('EMPLOYER', 'Employer')], max_length=20)),
                ('signature_text', models.CharField(help_text='Text or representation of signature', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('document_hash', models.CharField(help_text='SHA256 hash of the document signed', max_length=64)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(help_text='Contract being signed', on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='contracts.contract')),
                ('signer_user', models.ForeignKey(blank=True, db_constraint=False, help_text='User who signed (optional for magic links)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract Signature',
                'verbose_name_plural': 'Contract Signatures',
                'db_table': 'contract_signatures',
                'ordering': ['signed_at'],
            },
        ),
    ]
