# Generated by Django 5.2.8 on 2026-01-01 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_contractsignature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amendment_number', models.IntegerField(help_text='Sequential number of the amendment (1, 2, 3...)')),
                ('changed_fields', models.JSONField(default=dict, help_text='JSON Structure of changed fields (e.g., {"base_salary": {"old": 500000, "new": 550000}})')),
                ('effective_date', models.DateField(help_text='Date when this amendment takes effect')),
                ('document', models.FileField(blank=True, help_text='Amendment document (PDF/DOCX)', null=True, upload_to='contract_amendments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(help_text='Contract being amended', on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created the amendment', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract Amendment',
                'verbose_name_plural': 'Contract Amendments',
                'db_table': 'contract_amendments',
                'ordering': ['amendment_number'],
                'unique_together': {('contract', 'amendment_number')},
            },
        ),
    ]
