# Generated by Django 5.2.8 on 2026-02-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_alter_contract_final_pay_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowance',
            name='advantage',
            field=models.UUIDField(blank=True, help_text='Optional link to a payroll advantage catalog item', null=True),
        ),
        migrations.AddField(
            model_name='allowance',
            name='advantage_type',
            field=models.CharField(blank=True, help_text='Optional advantage type label/code', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='allowance',
            name='calculation_basis',
            field=models.CharField(blank=True, help_text='Optional calculation basis reference', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='allowance',
            name='cnps_majoration',
            field=models.CharField(blank=True, help_text='Optional CNPS-specific majoration rule', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='allowance',
            name='code',
            field=models.CharField(blank=True, help_text='Optional business code for this component', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='allowance',
            name='component_branch_id',
            field=models.UUIDField(blank=True, help_text='Optional branch reference for imported payroll metadata', null=True),
        ),
        migrations.AddField(
            model_name='allowance',
            name='component_user_id',
            field=models.IntegerField(blank=True, help_text='Optional user reference for imported payroll metadata', null=True),
        ),
        migrations.AddField(
            model_name='allowance',
            name='component_year',
            field=models.CharField(blank=True, help_text='Optional fiscal year reference (e.g., 2026)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='allowance',
            name='institution_id',
            field=models.IntegerField(blank=True, help_text='Optional institution reference for imported payroll metadata', null=True),
        ),
        migrations.AddField(
            model_name='allowance',
            name='is_contribution',
            field=models.BooleanField(blank=True, help_text='Is this allowance included in contribution calculations?', null=True),
        ),
        migrations.AddField(
            model_name='allowance',
            name='is_enable',
            field=models.BooleanField(default=True, help_text='Whether this component is enabled'),
        ),
        migrations.AddField(
            model_name='allowance',
            name='is_manual',
            field=models.BooleanField(blank=True, help_text='Whether this allowance is manually managed', null=True),
        ),
        migrations.AddField(
            model_name='allowance',
            name='is_nature',
            field=models.BooleanField(blank=True, help_text='Whether this is a benefit in kind', null=True),
        ),
        migrations.AddField(
            model_name='allowance',
            name='is_nature_cnps',
            field=models.BooleanField(blank=True, help_text='Whether benefit-in-kind CNPS rules apply', null=True),
        ),
        migrations.AddField(
            model_name='allowance',
            name='is_permanent',
            field=models.BooleanField(blank=True, help_text='Whether this allowance is permanent', null=True),
        ),
        migrations.AddField(
            model_name='allowance',
            name='is_variable',
            field=models.BooleanField(blank=True, help_text='Whether this allowance varies over time', null=True),
        ),
        migrations.AddField(
            model_name='allowance',
            name='majoration',
            field=models.CharField(blank=True, help_text='Optional allowance uplift/majoration rule', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='allowance',
            name='position',
            field=models.IntegerField(blank=True, help_text='Display/calculation order', null=True),
        ),
        migrations.AddField(
            model_name='allowance',
            name='sys',
            field=models.CharField(blank=True, help_text='Optional system/integration marker', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='allowance',
            name='taux',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Optional rate used for calculations', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='deduction',
            name='affectation',
            field=models.CharField(blank=True, help_text='Optional payroll affectation/impact area', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deduction',
            name='calculation_basis',
            field=models.CharField(blank=True, help_text='Optional calculation basis reference', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deduction',
            name='calculation_scale',
            field=models.CharField(blank=True, help_text='Optional calculation scale reference', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deduction',
            name='code',
            field=models.CharField(blank=True, help_text='Optional business code for this component', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deduction',
            name='component_branch_id',
            field=models.UUIDField(blank=True, help_text='Optional branch reference for imported payroll metadata', null=True),
        ),
        migrations.AddField(
            model_name='deduction',
            name='component_user_id',
            field=models.IntegerField(blank=True, help_text='Optional user reference for imported payroll metadata', null=True),
        ),
        migrations.AddField(
            model_name='deduction',
            name='component_year',
            field=models.CharField(blank=True, help_text='Optional fiscal year reference (e.g., 2026)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='deduction',
            name='deduction_base',
            field=models.CharField(blank=True, help_text='Optional upstream/base deduction reference', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deduction',
            name='deduction_basis',
            field=models.CharField(blank=True, help_text='Optional deduction basis reference', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deduction',
            name='deduction_type',
            field=models.CharField(blank=True, help_text='Optional deduction type label/code', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deduction',
            name='employee_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Optional employee-side deduction rate', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='deduction',
            name='employer_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Optional employer-side deduction rate', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='deduction',
            name='institution_id',
            field=models.IntegerField(blank=True, help_text='Optional institution reference for imported payroll metadata', null=True),
        ),
        migrations.AddField(
            model_name='deduction',
            name='is_base',
            field=models.BooleanField(blank=True, help_text='Whether this deduction acts as a base for others', null=True),
        ),
        migrations.AddField(
            model_name='deduction',
            name='is_count',
            field=models.BooleanField(blank=True, help_text='Whether this deduction is included in totals', null=True),
        ),
        migrations.AddField(
            model_name='deduction',
            name='is_employee',
            field=models.BooleanField(blank=True, help_text='Whether this deduction applies to the employee share', null=True),
        ),
        migrations.AddField(
            model_name='deduction',
            name='is_employer',
            field=models.BooleanField(blank=True, help_text='Whether this deduction applies to the employer share', null=True),
        ),
        migrations.AddField(
            model_name='deduction',
            name='is_enable',
            field=models.BooleanField(default=True, help_text='Whether this component is enabled'),
        ),
        migrations.AddField(
            model_name='deduction',
            name='is_rate',
            field=models.BooleanField(blank=True, help_text='Whether rate-based calculation is used', null=True),
        ),
        migrations.AddField(
            model_name='deduction',
            name='is_scale',
            field=models.BooleanField(blank=True, help_text='Whether scale table calculation is used', null=True),
        ),
        migrations.AddField(
            model_name='deduction',
            name='partner',
            field=models.CharField(blank=True, help_text='Optional beneficiary/partner institution', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deduction',
            name='position',
            field=models.IntegerField(blank=True, help_text='Display/calculation order', null=True),
        ),
        migrations.AddField(
            model_name='deduction',
            name='sys',
            field=models.CharField(blank=True, help_text='Optional system/integration marker', max_length=255, null=True),
        ),
    ]
