# Generated by Django 5.2.8 on 2026-02-12 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_allowance_advantage_allowance_advantage_type_and_more'),
        ('employees', '0002_remove_employeeconfiguration_require_employee_consent_cross_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Calculated or manual amount for this element and period', max_digits=12)),
                ('year', models.CharField(help_text='Year this element applies to (e.g., 2026)', max_length=10)),
                ('month', models.CharField(help_text='Month this element applies to (e.g., 01)', max_length=10)),
                ('employee_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Optional employee-side rate snapshot for this period', max_digits=7, null=True)),
                ('employer_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Optional employer-side rate snapshot for this period', max_digits=7, null=True)),
                ('institution_id', models.IntegerField(db_index=True, help_text='Employer/institution identifier owning this element')),
                ('user_id', models.IntegerField(blank=True, help_text='User that created/generated this element', null=True)),
                ('is_enable', models.BooleanField(default=True, help_text='Whether this element is active for payroll calculations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advantage', models.ForeignKey(blank=True, help_text='Advantage/allowance definition applied for this element', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='contracts.allowance')),
                ('branch', models.ForeignKey(blank=True, help_text='Optional branch scope for this element', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_elements', to='employees.branch')),
                ('contract', models.ForeignKey(help_text='Contract this payroll element belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='contracts.contract')),
                ('deduction', models.ForeignKey(blank=True, help_text='Deduction definition applied for this element', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='contracts.deduction')),
            ],
            options={
                'verbose_name': 'Contract Element',
                'verbose_name_plural': 'Contract Elements',
                'db_table': 'contract_elements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['contract', 'year', 'month'], name='contract_el_contrac_fa5a30_idx'), models.Index(fields=['institution_id', 'is_enable'], name='contract_el_institu_f723d7_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('advantage__isnull', False), ('deduction__isnull', True)), models.Q(('advantage__isnull', True), ('deduction__isnull', False)), _connector='OR'), name='contract_element_exactly_one_component')],
            },
        ),
    ]
