# Generated by Django 5.2.8 on 2026-01-01 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_contractamendment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='previous_contract',
            field=models.ForeignKey(blank=True, help_text='Previous contract if this is a renewal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='contracts.contract'),
        ),
    ]
