# Generated by Django 5.2.8 on 2026-02-12 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_contractelement'),
        ('employees', '0002_remove_employeeconfiguration_require_employee_consent_cross_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('employer_id', models.IntegerField(db_index=True, help_text='ID of the employer (from main database)')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('is_enable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculation_scales', to='employees.branch')),
            ],
            options={
                'verbose_name': 'Calculation Scale',
                'verbose_name_plural': 'Calculation Scales',
                'db_table': 'calculation_scales',
                'ordering': ['name', 'code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScaleRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range1', models.FloatField(blank=True, null=True)),
                ('range2', models.FloatField(blank=True, null=True)),
                ('coefficient', models.FloatField(blank=True, null=True)),
                ('indice', models.FloatField(blank=True, null=True)),
                ('base', models.FloatField(blank=True, null=True)),
                ('employer_id', models.IntegerField(db_index=True, help_text='ID of the employer (from main database)')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('is_enable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scale_ranges', to='employees.branch')),
                ('calculation_scale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='contracts.calculationscale')),
            ],
            options={
                'verbose_name': 'Scale Range',
                'verbose_name_plural': 'Scale Ranges',
                'db_table': 'scale_ranges',
                'ordering': ['calculation_scale_id', 'range1', 'range2', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='calculationscale',
            index=models.Index(fields=['employer_id', 'is_enable'], name='calc_scale_emp_enabled_idx'),
        ),
        migrations.AddIndex(
            model_name='scalerange',
            index=models.Index(fields=['employer_id', 'is_enable'], name='scale_range_emp_enabled_idx'),
        ),
        migrations.AddIndex(
            model_name='scalerange',
            index=models.Index(fields=['calculation_scale'], name='scale_range_scale_idx'),
        ),
    ]
