# Generated by Django 5.2.8 on 2026-01-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_contract_previous_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='final_pay_flag',
            field=models.BooleanField(default=False, help_text='Flag to trigger final payroll calculation'),
        ),
        migrations.AddField(
            model_name='contract',
            name='notice_served',
            field=models.BooleanField(default=False, help_text='Whether the required notice period was served'),
        ),
        migrations.AddField(
            model_name='contract',
            name='termination_date',
            field=models.DateField(blank=True, help_text='Date when the contract was terminated', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='termination_reason',
            field=models.TextField(blank=True, help_text='Reason for termination', null=True),
        ),
    ]
