# Generated by Django 5.2.8 on 2026-01-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_contract_final_pay_flag_contract_notice_served_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractaudit',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='JSON metadata for the action', null=True),
        ),
    ]
