# Generated by Django 5.2.8 on 2026-01-02 09:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_contractaudit_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('PENDING_SIGNATURE', 'Pending Signature'), ('SIGNED', 'Signed'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Current status of the contract', max_length=20),
        ),
        migrations.CreateModel(
            name='ContractConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer_id', models.IntegerField(db_index=True, help_text='ID of the employer (from main database)')),
                ('id_prefix', models.CharField(default='CNT', max_length=10)),
                ('id_year_format', models.CharField(choices=[('YYYY', 'YYYY'), ('YY', 'YY')], default='YYYY', max_length=4)),
                ('id_include_institution_code', models.BooleanField(default=False)),
                ('id_sequence_padding', models.IntegerField(default=5)),
                ('id_reset_sequence_yearly', models.BooleanField(default=True)),
                ('last_sequence_number', models.IntegerField(default=0)),
                ('max_backdate_days', models.IntegerField(default=30)),
                ('allow_future_contracts', models.BooleanField(default=True)),
                ('min_fixed_term_duration_days', models.IntegerField(default=30)),
                ('probation_must_end_before_contract', models.BooleanField(default=True)),
                ('min_wage', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_salary_without_approval', models.DecimalField(decimal_places=2, default=1000000, max_digits=12)),
                ('salary_scale_enforcement', models.CharField(choices=[('STRICT', 'Strict'), ('WARNING', 'Warning'), ('DISABLED', 'Disabled')], default='WARNING', max_length=20)),
                ('allow_salary_override', models.BooleanField(default=True)),
                ('require_gross_salary_gt_zero', models.BooleanField(default=True)),
                ('allow_duplicate_allowances', models.BooleanField(default=False)),
                ('auto_apply_default_allowances', models.BooleanField(default=True)),
                ('allow_manual_allowances', models.BooleanField(default=True)),
                ('allow_percentage_allowances', models.BooleanField(default=True)),
                ('max_allowance_percentage', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('approval_enabled', models.BooleanField(default=False)),
                ('approval_levels', models.JSONField(blank=True, default=list, help_text='List of roles: ["HR", "FINANCE", "CEO"]')),
                ('salary_thresholds', models.JSONField(blank=True, default=dict, help_text='Thresholds per level: {"FINANCE": 500000, "CEO": 1000000}')),
                ('signature_required', models.BooleanField(default=True)),
                ('signing_order', models.CharField(choices=[('EMPLOYEE_FIRST', 'Employee -> Employer'), ('EMPLOYER_FIRST', 'Employer -> Employee'), ('PARALLEL', 'Parallel')], default='EMPLOYEE_FIRST', max_length=20)),
                ('allow_activation_without_signature', models.BooleanField(default=False)),
                ('signature_reminder_interval_days', models.IntegerField(default=3)),
                ('signature_expiry_days', models.IntegerField(default=14)),
                ('allow_concurrent_contracts_same_inst', models.BooleanField(default=False)),
                ('allow_multi_institution_employment', models.BooleanField(default=False)),
                ('auto_expire_fixed_term', models.BooleanField(default=True)),
                ('auto_renew_option_available', models.BooleanField(default=False)),
                ('expiry_grace_period_days', models.IntegerField(default=0)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('days_before_expiry_notify', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contract Configuration',
                'verbose_name_plural': 'Contract Configurations',
                'db_table': 'contract_configurations',
                'unique_together': {('employer_id',)},
            },
        ),
        migrations.CreateModel(
            name='ContractTypeConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer_id', models.IntegerField(db_index=True)),
                ('contract_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('FIXED_TERM', 'Fixed-Term'), ('INTERNSHIP', 'Internship'), ('CONSULTANT', 'Consultant'), ('PART_TIME', 'Part-Time')], max_length=20)),
                ('default_duration_months', models.IntegerField(blank=True, null=True)),
                ('end_date_required', models.BooleanField(default=True)),
                ('default_probation_period_months', models.IntegerField(default=3)),
                ('overtime_eligible', models.BooleanField(default=True)),
                ('default_notice_period_days', models.IntegerField(default=30)),
                ('default_leave_policy', models.CharField(blank=True, max_length=100, null=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('requires_signature', models.BooleanField(default=True)),
                ('auto_activate_on_start', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_configs', to='contracts.contracttemplate')),
            ],
            options={
                'verbose_name': 'Contract Type Configuration',
                'verbose_name_plural': 'Contract Type Configurations',
                'db_table': 'contract_type_configurations',
                'unique_together': {('employer_id', 'contract_type')},
            },
        ),
    ]
