# Generated by Django 5.2.8 on 2026-02-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_backfill_contractelement_recurring_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractComponentTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employer_id', models.IntegerField(db_index=True)),
                ('component_type', models.CharField(choices=[('ADVANTAGE', 'Advantage'), ('DEDUCTION', 'Deduction')], db_index=True, max_length=16)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contract Component Template',
                'verbose_name_plural': 'Contract Component Templates',
                'db_table': 'contract_component_templates',
                'indexes': [models.Index(fields=['employer_id', 'component_type', 'is_active'], name='contract_co_employe_7f22da_idx')],
                'constraints': [models.UniqueConstraint(fields=('employer_id', 'component_type', 'code'), name='uniq_contract_component_template_code_per_employer')],
            },
        ),
    ]
