# Generated by Django 5.2.8 on 2026-01-02 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_alter_contract_status_contractconfiguration_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contractconfiguration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contractconfiguration',
            name='auto_activate_on_start',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contractconfiguration',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('PERMANENT', 'Permanent'), ('FIXED_TERM', 'Fixed-Term'), ('INTERNSHIP', 'Internship'), ('CONSULTANT', 'Consultant'), ('PART_TIME', 'Part-Time')], help_text='Null for global settings, or specific type for overrides', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contractconfiguration',
            name='default_duration_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractconfiguration',
            name='default_leave_policy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contractconfiguration',
            name='default_notice_period_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='contractconfiguration',
            name='default_probation_period_months',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='contractconfiguration',
            name='default_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configurations', to='contracts.contracttemplate'),
        ),
        migrations.AddField(
            model_name='contractconfiguration',
            name='end_date_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contractconfiguration',
            name='overtime_eligible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contractconfiguration',
            name='requires_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractconfiguration',
            name='requires_signature',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='contractconfiguration',
            unique_together={('employer_id', 'contract_type')},
        ),
        migrations.DeleteModel(
            name='ContractTypeConfiguration',
        ),
    ]
