# Generated by Django 5.2.8 on 2026-01-05 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_alter_contractconfiguration_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='institution',
        ),
    ]
