# Generated by Django 5.2.11 on 2026-02-26 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_contractconfiguration_global_unique'),
        ('contracts', '0013_ensure_component_month_columns'),
    ]

    operations = [
    ]
