# Generated by Django 5.2.8 on 2026-01-08 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0014_merge_0006_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryScale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer_id', models.IntegerField(db_index=True, help_text='ID of the employer (from main database)')),
                ('salary_category', models.CharField(help_text='Salary category', max_length=255)),
                ('echelon', models.CharField(help_text='Echelon', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Salary amount', max_digits=12)),
                ('status', models.CharField(choices=[('ENABLED', 'Enabled'), ('DISABLED', 'Disabled')], default='ENABLED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salary Scale',
                'verbose_name_plural': 'Salary Scales',
                'db_table': 'salary_scales',
                'ordering': ['salary_category', 'echelon'],
                'indexes': [
                    models.Index(fields=['employer_id', 'status'], name='salary_scale_emp_status_idx'),
                    models.Index(fields=['employer_id', 'salary_category'], name='salary_scale_emp_cat_idx'),
                ],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='job_position',
            field=models.CharField(blank=True, help_text='Job position or title for this contract', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='salary_scale',
            field=models.ForeignKey(blank=True, help_text='Salary scale for this contract', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='contracts.salaryscale'),
        ),
    ]
