# Generated by Django 5.2.9 on 2026-01-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0015_salary_scale_and_job_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractconfiguration',
            name='attendance_configuration',
            field=models.JSONField(blank=True, default=dict, help_text='Work rules (schedule type, shift template, attendance requirements)'),
        ),
        migrations.AddField(
            model_name='contractconfiguration',
            name='expense_configuration',
            field=models.JSONField(blank=True, default=dict, help_text='Expense routing (policy, cost center, reimbursement)'),
        ),
        migrations.AddField(
            model_name='contractconfiguration',
            name='fleet_configuration',
            field=models.JSONField(blank=True, default=dict, help_text='Fleet entitlements (vehicle, transport allowance)'),
        ),
        migrations.AddField(
            model_name='contractconfiguration',
            name='governance_configuration',
            field=models.JSONField(blank=True, default=dict, help_text='Governance/audit defaults (approval/activation ownership)'),
        ),
        migrations.AddField(
            model_name='contractconfiguration',
            name='payroll_configuration',
            field=models.JSONField(blank=True, default=dict, help_text='Payroll inputs (tax profile, CNPS, probation, proration)'),
        ),
        migrations.AddField(
            model_name='contractconfiguration',
            name='recruitment_configuration',
            field=models.JSONField(blank=True, default=dict, help_text='Recruitment metadata defaults (application IDs, offer refs, etc.)'),
        ),
        migrations.AddField(
            model_name='contractconfiguration',
            name='signature_configuration',
            field=models.JSONField(blank=True, default=dict, help_text='Document & signature defaults (template, method, document hash)'),
        ),
        migrations.AddField(
            model_name='contractconfiguration',
            name='time_off_configuration',
            field=models.JSONField(blank=True, default=dict, help_text='Leave policy defaults & overrides per leave type'),
        ),
        migrations.AddField(
            model_name='contractconfiguration',
            name='treasury_configuration',
            field=models.JSONField(blank=True, default=dict, help_text='Treasury preferences (payment priority/channel)'),
        ),
    ]
