# Generated by Django 5.2.9 on 2026-01-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseclaim',
            name='payment_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='payment_failed_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='treasury_external_reference',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVAL_PENDING', 'Approval Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('PAID', 'Paid')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='incomerecord',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVAL_PENDING', 'Approval Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
