# Generated by Django 5.2.9 on 2026-01-26 09:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('is_admin', models.BooleanField(default=False, help_text='Designates whether the user is a super admin')),
                ('is_employer', models.BooleanField(default=False, help_text='Designates whether the user is an employer')),
                ('is_employee', models.BooleanField(default=False, help_text='Designates whether the user is an employee')),
                ('profile_completed', models.BooleanField(default=False, help_text='Designates whether the user has completed their profile')),
                ('two_factor_enabled', models.BooleanField(default=False, help_text='Designates whether 2FA is enabled')),
                ('two_factor_secret', models.CharField(blank=True, help_text='TOTP secret for 2FA', max_length=32, null=True)),
                ('last_active_employer_id', models.IntegerField(blank=True, db_index=True, help_text='EmployerProfile ID most recently used by the user', null=True)),
                ('signature', models.ImageField(blank=True, help_text='Stored user signature image', null=True, upload_to='user_signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ActivationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activation Token',
                'verbose_name_plural': 'Activation Tokens',
                'db_table': 'activation_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], max_length=20)),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], max_length=20)),
                ('nationality', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('alternative_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state_region', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(max_length=100)),
                ('emergency_contact_name', models.CharField(max_length=200)),
                ('emergency_contact_relationship', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('national_id_number', models.CharField(max_length=50, unique=True)),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('desired_position', models.CharField(blank=True, max_length=255, null=True)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('highest_education_level', models.CharField(blank=True, max_length=100, null=True)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated list of skills', null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='employee_profiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_registry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Registry',
                'verbose_name_plural': 'Employee Registry',
                'db_table': 'employee_registry',
            },
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('employer_name_or_group', models.CharField(max_length=255)),
                ('organization_type', models.CharField(choices=[('PRIVATE', 'Private Company'), ('NGO', 'Non-Governmental Organization'), ('GOVERNMENT', 'Government Agency'), ('PUBLIC', 'Public Company'), ('PARTNERSHIP', 'Partnership'), ('SOLE_PROPRIETOR', 'Sole Proprietorship'), ('OTHER', 'Other')], max_length=50)),
                ('industry_sector', models.CharField(max_length=255)),
                ('date_of_incorporation', models.DateField()),
                ('company_location', models.CharField(help_text='City/Region', max_length=255)),
                ('physical_address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('fax_number', models.CharField(blank=True, max_length=20, null=True)),
                ('official_company_email', models.EmailField(max_length=254)),
                ('rccm', models.CharField(help_text='Trade & Personal Property Credit Register', max_length=100)),
                ('taxpayer_identification_number', models.CharField(help_text='NIU', max_length=50)),
                ('cnps_employer_number', models.CharField(help_text='CNPS Employer Number', max_length=50)),
                ('labour_inspectorate_declaration', models.CharField(max_length=100)),
                ('business_license', models.CharField(help_text='Patente', max_length=100)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('bank_iban_swift', models.CharField(blank=True, help_text='IBAN/SWIFT code if applicable', max_length=50, null=True)),
                ('database_name', models.CharField(blank=True, help_text='Tenant database name', max_length=100, null=True, unique=True)),
                ('database_created', models.BooleanField(default=False, help_text='Whether tenant database has been created')),
                ('database_created_at', models.DateTimeField(blank=True, help_text='When the tenant database was created', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employer Profile',
                'verbose_name_plural': 'Employer Profiles',
                'db_table': 'employer_profiles',
            },
        ),
        migrations.CreateModel(
            name='EmployeeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('ACTIVE', 'Active'), ('TERMINATED', 'Terminated')], default='INVITED', max_length=20)),
                ('role', models.CharField(blank=True, choices=[('EMPLOYEE', 'Employee'), ('MANAGER', 'Manager'), ('HR', 'HR'), ('ADMIN', 'Admin')], help_text='Optional role label', max_length=30, null=True)),
                ('permissions', models.JSONField(blank=True, help_text='Optional per-employer permissions', null=True)),
                ('tenant_employee_id', models.CharField(blank=True, help_text='Employee PK inside the employer tenant database (supports UUIDs)', max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('employer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_memberships', to='accounts.employerprofile')),
            ],
            options={
                'verbose_name': 'Employee Membership',
                'verbose_name_plural': 'Employee Memberships',
                'db_table': 'employee_memberships',
                'indexes': [models.Index(fields=['user', 'status'], name='employee_me_user_id_5b6197_idx'), models.Index(fields=['employer_profile', 'status'], name='employee_me_employe_bff082_idx')],
                'unique_together': {('user', 'employer_profile')},
            },
        ),
    ]
