# Generated by Django 5.2.9 on 2025-12-13 11:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('is_admin', models.BooleanField(default=False, help_text='Designates whether the user is a super admin')),
                ('is_employer', models.BooleanField(default=False, help_text='Designates whether the user is an employer')),
                ('profile_completed', models.BooleanField(default=False, help_text='Designates whether the employer has completed their profile')),
                ('two_factor_enabled', models.BooleanField(default=False, help_text='Designates whether 2FA is enabled')),
                ('two_factor_secret', models.CharField(blank=True, help_text='TOTP secret for 2FA', max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ActivationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activation Token',
                'verbose_name_plural': 'Activation Tokens',
                'db_table': 'activation_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('employer_name_or_group', models.CharField(max_length=255)),
                ('organization_type', models.CharField(choices=[('PRIVATE', 'Private Company'), ('NGO', 'Non-Governmental Organization'), ('GOVERNMENT', 'Government Agency'), ('PUBLIC', 'Public Company'), ('PARTNERSHIP', 'Partnership'), ('SOLE_PROPRIETOR', 'Sole Proprietorship'), ('OTHER', 'Other')], max_length=50)),
                ('industry_sector', models.CharField(max_length=255)),
                ('date_of_incorporation', models.DateField()),
                ('company_location', models.CharField(help_text='City/Region', max_length=255)),
                ('physical_address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('fax_number', models.CharField(blank=True, max_length=20, null=True)),
                ('official_company_email', models.EmailField(max_length=254)),
                ('rccm', models.CharField(help_text='Trade & Personal Property Credit Register', max_length=100)),
                ('taxpayer_identification_number', models.CharField(help_text='NIU', max_length=50)),
                ('cnps_employer_number', models.CharField(help_text='CNPS Employer Number', max_length=50)),
                ('labour_inspectorate_declaration', models.CharField(max_length=100)),
                ('business_license', models.CharField(help_text='Patente', max_length=100)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('bank_iban_swift', models.CharField(blank=True, help_text='IBAN/SWIFT code if applicable', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employer Profile',
                'verbose_name_plural': 'Employer Profiles',
                'db_table': 'employer_profiles',
            },
        ),
    ]
