# Generated by Django 5.2.9 on 2026-01-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.ImageField(blank=True, help_text='Stored user signature image', null=True, upload_to='user_signatures/'),
        ),
    ]
