# Generated by Django 5.2.9 on 2025-12-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_employee_alter_user_profile_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='database_created',
            field=models.BooleanField(default=False, help_text='Whether tenant database has been created'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='database_created_at',
            field=models.DateTimeField(blank=True, help_text='When the tenant database was created', null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='database_name',
            field=models.CharField(blank=True, help_text='Tenant database name', max_length=100, null=True, unique=True),
        ),
    ]
