# Generated by Django 5.2.8 on 2026-01-29 07:45

from django.db import migrations, models


def dedupe_employee_roles(apps, schema_editor):
    EmployeeRole = apps.get_model('accounts', 'EmployeeRole')

    duplicates = (
        EmployeeRole.objects.values('employer_id', 'employee_id')
        .annotate(role_count=models.Count('id'))
        .filter(role_count__gt=1)
    )

    for entry in duplicates:
        qs = EmployeeRole.objects.filter(
            employer_id=entry['employer_id'],
            employee_id=entry['employee_id'],
        ).order_by('-assigned_at', '-id')
        keep = qs.first()
        if keep:
            qs.exclude(id=keep.id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_permission_user_is_employer_owner_role_employeerole_and_more'),
    ]

    operations = [
        migrations.RunPython(dedupe_employee_roles, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='employeerole',
            unique_together={('employer', 'employee_id')},
        ),
    ]
