# Generated by Django 5.2.8 on 2026-01-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_employeerole_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_employer_owner',
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='EmployeeRole',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='RolePermission',
        ),
        migrations.DeleteModel(
            name='UserPermissionOverride',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
