# Generated by Codex on 2026-01-30

import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_employer_owners(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    EmployerProfile = apps.get_model("accounts", "EmployerProfile")
    owner_ids = EmployerProfile.objects.values_list("user_id", flat=True)
    User.objects.filter(id__in=owner_ids).update(is_employer_owner=True)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_employeerole_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_employer_owner",
            field=models.BooleanField(
                default=False, help_text="Designates whether the user is the employer owner"
            ),
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=200, unique=True)),
                ("module", models.CharField(db_index=True, max_length=50)),
                ("resource", models.CharField(max_length=50)),
                ("action", models.CharField(max_length=50)),
                ("scope", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
                "db_table": "rbac_permissions",
                "ordering": ["module", "resource", "action", "scope"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_system_role", models.BooleanField(default=False, help_text="Template/system role indicator")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "allow_high_risk_combination",
                    models.BooleanField(
                        default=False,
                        help_text="Allow payroll input + treasury release combinations (owner only).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roles_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="accounts.employerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "db_table": "rbac_roles",
                "indexes": [
                    models.Index(fields=["employer", "is_active"], name="rbac_roles_employe_e2effa_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="EmployeeRole",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "employee_id",
                    models.CharField(
                        db_index=True,
                        help_text="Employee PK inside the employer tenant database (supports UUIDs)",
                        max_length=64,
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("COMPANY", "Company"),
                            ("BRANCH", "Branch"),
                            ("DEPARTMENT", "Department"),
                            ("SELF", "Self"),
                        ],
                        default="COMPANY",
                        max_length=20,
                    ),
                ),
                (
                    "scope_id",
                    models.CharField(
                        blank=True,
                        help_text="Optional branch/department scope identifier (UUID as string).",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roles_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_roles",
                        to="accounts.employerprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_roles",
                        to="accounts.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Role",
                "verbose_name_plural": "Employee Roles",
                "db_table": "rbac_employee_roles",
                "indexes": [
                    models.Index(fields=["employer", "employee_id"], name="rbac_employ_employe_10f5fd_idx"),
                    models.Index(fields=["user", "employer"], name="rbac_employ_user_id_79f65d_idx"),
                ],
                "unique_together": {("employer", "employee_id", "role", "scope_type", "scope_id")},
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="accounts.permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="accounts.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Permission",
                "verbose_name_plural": "Role Permissions",
                "db_table": "rbac_role_permissions",
                "indexes": [
                    models.Index(fields=["role", "permission"], name="rbac_role_p_role_id_cb90bc_idx")
                ],
                "unique_together": {("role", "permission")},
            },
        ),
        migrations.CreateModel(
            name="UserPermissionOverride",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("effect", models.CharField(choices=[("ALLOW", "Allow"), ("DENY", "Deny")], max_length=10)),
                ("reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permission_overrides_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_overrides",
                        to="accounts.employerprofile",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_overrides",
                        to="accounts.permission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Permission Override",
                "verbose_name_plural": "User Permission Overrides",
                "db_table": "rbac_user_permission_overrides",
                "indexes": [
                    models.Index(fields=["employer", "user"], name="rbac_user_p_employe_032743_idx")
                ],
                "unique_together": {("employer", "user", "permission")},
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("action", models.CharField(max_length=100)),
                ("entity_type", models.CharField(max_length=50)),
                ("entity_id", models.CharField(max_length=64)),
                ("meta_old", models.TextField(blank=True, null=True)),
                ("meta_new", models.TextField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="accounts.employerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "rbac_audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["employer", "created_at"], name="rbac_audit__employe_375824_idx"),
                    models.Index(fields=["action"], name="rbac_audit__action_3a4c98_idx"),
                ],
            },
        ),
        migrations.RunPython(set_employer_owners, migrations.RunPython.noop),
    ]

