# Generated by Django 5.2.9 on 2026-01-19 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_backfill_employee_memberships'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='employeemembership',
            new_name='employee_me_user_id_5b6197_idx',
            old_name='employee_m_user_id_c2b68d_idx',
        ),
        migrations.RenameIndex(
            model_name='employeemembership',
            new_name='employee_me_employe_bff082_idx',
            old_name='employee_m_employe_69ea07_idx',
        ),
    ]
