# Generated by Django 5.2.9 on 2026-02-03 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_employer_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('employer', 'name')},
        ),
    ]
