# Generated by Django 5.2.9 on 2026-02-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_add_employer_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="employerprofile",
            name="company_logo",
            field=models.ImageField(blank=True, null=True, upload_to="company_logos/"),
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="company_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1-10", "1-10"),
                    ("11-50", "11-50"),
                    ("51-200", "51-200"),
                    ("201-500", "201-500"),
                    ("501-1000", "501-1000"),
                    ("1000+", "1000+"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="company_tagline",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="company_overview",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="company_website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="careers_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
