# Generated by Django 5.2.9 on 2026-02-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_employer_public_profile_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employerprofile",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="employerprofile",
            name="bank_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
