# Generated by Django 5.2.9 on 2026-02-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_make_bank_fields_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="employerprofile",
            name="company_mission",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="company_values",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employerprofile",
            name="company_benefits",
            field=models.TextField(blank=True, null=True),
        ),
    ]
