# Generated by Django 5.2.11 on 2026-02-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_employer_profile_public_extras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='allow_high_risk_combination',
            field=models.BooleanField(default=False, help_text='Allow high-risk input + treasury release combinations (owner only).'),
        ),
    ]
