# Generated by Django 5.2.9 on 2026-02-25 05:58

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_role_allow_high_risk_combination'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeregistry',
            name='default_consent_scopes',
            field=models.JSONField(blank=True, default=accounts.models.default_consent_scopes, help_text='Default data sharing scopes preferred by the employee'),
        ),
    ]
