# Generated by Django 5.2.11 on 2026-02-12

import django.db.models.deletion
from django.db import migrations, models
from django.db.utils import OperationalError, ProgrammingError


def copy_advantage_code_to_allowance_code(apps, schema_editor):
    # Some tenant databases have payroll.0001 marked as applied from an older
    # branch/state where payroll_advantages never existed. In that case, the
    # join below must be skipped to let schema migration continue.
    existing_tables = set(schema_editor.connection.introspection.table_names())
    if "payroll_basis_advantages" not in existing_tables:
        return
    if "payroll_advantages" not in existing_tables:
        return

    basis_model = apps.get_model("payroll", "CalculationBasisAdvantage")
    try:
        queryset = basis_model.objects.filter(allowance_code__isnull=True).select_related("advantage")
        for row in queryset:
            advantage = getattr(row, "advantage", None)
            if not advantage:
                continue
            row.allowance_code = getattr(advantage, "code", None)
            if row.allowance_code:
                row.save(update_fields=["allowance_code"])
    except (ProgrammingError, OperationalError):
        # Keep migration resilient across tenant DBs with legacy schema drift.
        return


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0009_calculationscale_scalerange_and_more"),
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculationbasisadvantage",
            name="allowance",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional direct link to an allowance.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="basis_links",
                to="contracts.allowance",
            ),
        ),
        migrations.AddField(
            model_name="calculationbasisadvantage",
            name="allowance_code",
            field=models.CharField(
                blank=True,
                help_text="Optional code-based mapping when allowance rows differ per contract.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="salaryadvantage",
            name="allowance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contracts.allowance",
            ),
        ),
        migrations.AlterField(
            model_name="salaryadvantage",
            name="code",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="salarydeduction",
            name="code",
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name="salarydeduction",
            name="deduction",
        ),
        migrations.AddField(
            model_name="salarydeduction",
            name="deduction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contracts.deduction",
            ),
        ),
        migrations.RunPython(copy_advantage_code_to_allowance_code, noop_reverse),
        migrations.AlterUniqueTogether(
            name="calculationbasisadvantage",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="calculationbasisadvantage",
            name="advantage",
        ),
        migrations.RemoveField(
            model_name="salaryadvantage",
            name="advantage",
        ),
        migrations.AddIndex(
            model_name="calculationbasisadvantage",
            index=models.Index(fields=["employer_id", "is_active"], name="payroll_bas_employe_9228f5_idx"),
        ),
        migrations.AddConstraint(
            model_name="calculationbasisadvantage",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("allowance__isnull", False), ("allowance_code__isnull", True)),
                    models.Q(("allowance__isnull", True), ("allowance_code__isnull", False)),
                    _connector="OR",
                ),
                name="payroll_basis_advantage_single_mapping",
            ),
        ),
        migrations.AddConstraint(
            model_name="calculationbasisadvantage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("allowance__isnull", False)),
                fields=("employer_id", "basis", "allowance"),
                name="uniq_payroll_basis_allowance_link",
            ),
        ),
        migrations.AddConstraint(
            model_name="calculationbasisadvantage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("allowance_code__isnull", False)),
                fields=("employer_id", "basis", "allowance_code"),
                name="uniq_payroll_basis_allowance_code_link",
            ),
        ),
        migrations.DeleteModel(
            name="PayrollElement",
        ),
        migrations.DeleteModel(
            name="ScaleRange",
        ),
        migrations.DeleteModel(
            name="Deduction",
        ),
        migrations.DeleteModel(
            name="Advantage",
        ),
        migrations.DeleteModel(
            name="CalculationScale",
        ),
    ]
