# Generated by Django 5.2.11 on 2026-02-12 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_contract_based_payroll_schema'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='calculationbasisadvantage',
            new_name='payroll_bas_employe_e7e551_idx',
            old_name='payroll_bas_employe_9228f5_idx',
        ),
        migrations.AlterField(
            model_name='calculationbasisadvantage',
            name='basis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowance_links', to='payroll.calculationbasis'),
        ),
    ]
