# Generated by Django 5.2.11 on 2026-02-17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0003_rename_payroll_bas_employe_9228f5_idx_payroll_bas_employe_e7e551_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payrollconfiguration",
            name="cac_rate_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10.00"),
                help_text="CAC rate as a percentage of IRPP amount.",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="payrollconfiguration",
            name="irpp_withholding_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("62000.00"),
                help_text="Monthly taxable gross threshold below which IRPP withholding is not applied.",
                max_digits=12,
            ),
        ),
    ]
