# Generated by Django 5.2.8 on 2026-02-25 12:05

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_backfill_contractelement_recurring_period'),
        ('employees', '0004_employeeconfiguration_multi_branch_enabled'),
        ('payroll', '0004_payrollconfiguration_threshold_and_cac_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePayrollImpactConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer_id', models.IntegerField(db_index=True)),
                ('event_code', models.CharField(choices=[('LATENESS', 'Lateness'), ('ABSENCE', 'Absence'), ('OVERTIME', 'Overtime'), ('EARLY_DEPARTURE', 'Early Departure'), ('WEEKEND_WORK', 'Weekend Work'), ('HOLIDAY_WORK', 'Holiday Work'), ('UNPAID_LEAVE', 'Unpaid Leave')], max_length=32)),
                ('affects_payroll', models.BooleanField(default=False)),
                ('bucket', models.CharField(choices=[('DEDUCTION', 'Deduction'), ('ADVANTAGE', 'Advantage')], default='DEDUCTION', max_length=16)),
                ('calc_method', models.CharField(choices=[('FIXED_AMOUNT', 'Fixed Amount'), ('PER_MINUTE', 'Per Minute'), ('PER_HOUR', 'Per Hour'), ('PER_DAY', 'Per Day'), ('PERCENT_OF_DAILY_RATE', 'Percent Of Daily Rate'), ('PERCENT_OF_BASIC_SALARY', 'Percent Of Basic Salary'), ('MULTIPLIER_OF_HOURLY_RATE', 'Multiplier Of Hourly Rate')], default='FIXED_AMOUNT', max_length=40)),
                ('value', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('multiplier', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('grace_minutes', models.IntegerField(blank=True, null=True)),
                ('cap_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('requires_validation', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_impact_configs', to='contracts.allowance')),
                ('deduction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_impact_configs', to='contracts.deduction')),
            ],
            options={
                'verbose_name': 'Attendance Payroll Impact Configuration',
                'verbose_name_plural': 'Attendance Payroll Impact Configurations',
                'db_table': 'payroll_attendance_impact_configs',
                'indexes': [models.Index(fields=['employer_id', 'is_active'], name='payroll_att_employe_6dbcbc_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('employer_id', 'event_code'), name='uniq_active_attendance_impact_per_event')],
            },
        ),
        migrations.CreateModel(
            name='PayrollGeneratedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer_id', models.IntegerField(db_index=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('source_type', models.CharField(choices=[('ATTENDANCE', 'Attendance')], default='ATTENDANCE', max_length=20)),
                ('source_event_code', models.CharField(choices=[('LATENESS', 'Lateness'), ('ABSENCE', 'Absence'), ('OVERTIME', 'Overtime'), ('EARLY_DEPARTURE', 'Early Departure'), ('WEEKEND_WORK', 'Weekend Work'), ('HOLIDAY_WORK', 'Holiday Work'), ('UNPAID_LEAVE', 'Unpaid Leave')], max_length=32)),
                ('source_record_id', models.UUIDField(blank=True, null=True)),
                ('source_date_range_key', models.CharField(blank=True, max_length=80, null=True)),
                ('bucket', models.CharField(choices=[('DEDUCTION', 'Deduction'), ('ADVANTAGE', 'Advantage')], max_length=16)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('unit_rate', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('LOCKED', 'Locked')], default='DRAFT', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_payroll_items', to='contracts.allowance')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_payroll_items', to='contracts.contract')),
                ('deduction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_payroll_items', to='contracts.deduction')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_payroll_items', to='employees.employee')),
                ('salary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_items', to='payroll.salary')),
            ],
            options={
                'verbose_name': 'Payroll Generated Item',
                'verbose_name_plural': 'Payroll Generated Items',
                'db_table': 'payroll_generated_items',
                'indexes': [models.Index(fields=['employer_id', 'year', 'month'], name='payroll_gen_employe_a8465c_idx'), models.Index(fields=['employee', 'year', 'month'], name='payroll_gen_employe_1fd9f1_idx'), models.Index(fields=['salary'], name='payroll_gen_salary__30d0f6_idx'), models.Index(fields=['contract', 'year', 'month'], name='payroll_gen_contrac_6464fc_idx'), models.Index(fields=['source_type', 'source_event_code'], name='payroll_gen_source__450997_idx')],
            },
        ),
    ]
