# Generated by Django 5.2.8 on 2026-02-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0005_attendancepayrollimpactconfig_payrollgenerateditem"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancepayrollimpactconfig",
            name="target_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Contract configuration component code (deduction/advantage template code).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="attendancepayrollimpactconfig",
            name="target_name",
            field=models.CharField(
                blank=True,
                help_text="Optional display name from the selected contract configuration component template.",
                max_length=255,
                null=True,
            ),
        ),
    ]

