# Generated by Django 5.2.11 on 2026-02-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentline',
            name='linked_object_type',
            field=models.CharField(choices=[('PAYSLIP', 'Salary Statement'), ('EXPENSE_CLAIM', 'Expense Claim'), ('BILL', 'Bill'), ('NONE', 'None')], default='NONE', max_length=20),
        ),
    ]
