# Generated by Django 5.2.9 on 2026-01-26 09:06

import django.db.models.deletion
import frontdesk.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontdeskStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer_id', models.IntegerField(db_index=True, help_text='ID of the employer (from main database)')),
                ('name', models.CharField(max_length=255)),
                ('kiosk_slug', models.CharField(default=frontdesk.models.generate_kiosk_slug, help_text='Stable slug used to build kiosk/QR URLs', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_self_check_in', models.BooleanField(default=True, help_text='Allow kiosk/QR self check-in (checkout remains manual)')),
                ('kiosk_theme', models.JSONField(blank=True, default=dict, help_text='Appearance settings for the kiosk (colors, typography, layout text)')),
                ('kiosk_logo', models.ImageField(blank=True, help_text='Optional logo displayed on the kiosk UI (uploaded file instead of external URL).', null=True, upload_to='frontdesk/kiosk_logos/')),
                ('terms_and_conditions', models.TextField(blank=True, help_text='Optional terms displayed on the kiosk')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frontdesk_stations', to='employees.branch')),
            ],
            options={
                'verbose_name': 'Frontdesk Station',
                'verbose_name_plural': 'Frontdesk Stations',
                'db_table': 'frontdesk_stations',
                'ordering': ['branch__name', '-is_active', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StationResponsible',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frontdesk_responsibilities', to='employees.employee')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_responsibles', to='frontdesk.frontdeskstation')),
            ],
            options={
                'verbose_name': 'Station Responsible',
                'verbose_name_plural': 'Station Responsibles',
                'db_table': 'frontdesk_station_responsibles',
                'unique_together': {('station', 'employee')},
            },
        ),
        migrations.AddField(
            model_name='frontdeskstation',
            name='responsibles',
            field=models.ManyToManyField(blank=True, related_name='managed_frontdesk_stations', through='frontdesk.StationResponsible', to='employees.employee'),
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer_id', models.IntegerField(db_index=True, help_text='ID of the employer (from main database)')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('id_type', models.CharField(blank=True, help_text='ID type provided (e.g., Passport, ID Card)', max_length=100, null=True)),
                ('id_number', models.CharField(blank=True, help_text='ID number captured at check-in', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
                'db_table': 'frontdesk_visitors',
                'indexes': [models.Index(fields=['employer_id', 'full_name'], name='frontdesk_v_employe_815b8e_idx'), models.Index(fields=['employer_id', 'phone'], name='frontdesk_v_employe_37f97c_idx'), models.Index(fields=['employer_id', 'email'], name='frontdesk_v_employe_70c0e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer_id', models.IntegerField(db_index=True, help_text='ID of the employer (from main database)')),
                ('visit_type', models.CharField(choices=[('WALK_IN', 'Walk-in'), ('PLANNED', 'Planned')], default='WALK_IN', max_length=10)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('CHECKED_IN', 'Checked In'), ('CHECKED_OUT', 'Checked Out'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=12)),
                ('visit_purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('planned_start', models.DateTimeField(blank=True, null=True)),
                ('planned_end', models.DateTimeField(blank=True, null=True)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('check_in_method', models.CharField(choices=[('MANUAL', 'Manual'), ('KIOSK', 'Kiosk/QR')], default='MANUAL', max_length=10)),
                ('check_out_by_id', models.IntegerField(blank=True, help_text='User ID of HR/Admin who completed checkout. Visitors never self checkout.', null=True)),
                ('kiosk_session_reference', models.CharField(blank=True, help_text='Optional kiosk session/QR reference captured at check-in', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frontdesk_visits', to='employees.branch')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hosted_visits', to='employees.employee')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='frontdesk.frontdeskstation')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='frontdesk.visitor')),
            ],
            options={
                'verbose_name': 'Visit',
                'verbose_name_plural': 'Visits',
                'db_table': 'frontdesk_visits',
                'indexes': [models.Index(fields=['employer_id', 'branch'], name='frontdesk_v_employe_db641a_idx'), models.Index(fields=['employer_id', 'status'], name='frontdesk_v_employe_dfd5d7_idx'), models.Index(fields=['employer_id', 'visit_type'], name='frontdesk_v_employe_e181f1_idx')],
            },
        ),
    ]
