# Generated by Django 5.2.9 on 2026-01-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employeedocument_document_type'),
        ('frontdesk', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='visit',
            new_name='frontdesk_v_employe_db641a_idx',
            old_name='frontdesk_v_employe_e143b0_idx',
        ),
        migrations.RenameIndex(
            model_name='visit',
            new_name='frontdesk_v_employe_dfd5d7_idx',
            old_name='frontdesk_v_employe_49389e_idx',
        ),
        migrations.RenameIndex(
            model_name='visit',
            new_name='frontdesk_v_employe_e181f1_idx',
            old_name='frontdesk_v_employe_3fa635_idx',
        ),
        migrations.RenameIndex(
            model_name='visitor',
            new_name='frontdesk_v_employe_815b8e_idx',
            old_name='frontdesk_v_employe_0c2bfc_idx',
        ),
        migrations.RenameIndex(
            model_name='visitor',
            new_name='frontdesk_v_employe_37f97c_idx',
            old_name='frontdesk_v_employe_a07e24_idx',
        ),
        migrations.RenameIndex(
            model_name='visitor',
            new_name='frontdesk_v_employe_70c0e9_idx',
            old_name='frontdesk_v_employe_ba3ab5_idx',
        ),
        migrations.AddField(
            model_name='frontdeskstation',
            name='responsibles',
            field=models.ManyToManyField(blank=True, related_name='managed_frontdesk_stations', through='frontdesk.StationResponsible', to='employees.employee'),
        ),
    ]
