# Generated by Django 5.2.9 on 2026-01-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontdesk', '0002_rename_frontdesk_v_employe_e143b0_idx_frontdesk_v_employe_db641a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontdeskstation',
            name='kiosk_logo',
            field=models.ImageField(blank=True, help_text='Optional logo displayed on the kiosk UI (uploaded file instead of external URL).', null=True, upload_to='frontdesk/kiosk_logos/'),
        ),
        migrations.AlterField(
            model_name='frontdeskstation',
            name='kiosk_theme',
            field=models.JSONField(blank=True, default=dict, help_text='Appearance settings for the kiosk (colors, typography, layout text)'),
        ),
    ]
