# Generated by Django 5.2.9 on 2026-01-15 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("frontdesk", "0003_frontdeskstation_kiosk_logo_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="frontdeskstation",
            name="unique_active_frontdesk_station_per_branch",
        ),
    ]
