# Generated by Django 5.2.9 on 2026-01-10 21:49

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employeedocument_document_type'),
        ('timeoff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOffRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer_id', models.IntegerField(db_index=True, help_text='Employer/tenant identifier (main DB)')),
                ('leave_type_code', models.CharField(db_index=True, max_length=50)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('unit', models.CharField(choices=[('DAYS', 'Days'), ('HALF_DAYS', 'Half Days'), ('HOURS', 'Hours')], default='DAYS', max_length=10)),
                ('duration_minutes', models.IntegerField(help_text='Normalized duration in minutes')),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=15)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(db_index=True, help_text='User ID from main DB')),
                ('updated_by', models.IntegerField(db_index=True, help_text='User ID from main DB')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Device/location/additional context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='Employee requesting time off', on_delete=django.db.models.deletion.CASCADE, related_name='time_off_requests', to='employees.employee')),
            ],
            options={
                'db_table': 'timeoff_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeOffLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer_id', models.IntegerField(db_index=True, help_text='Employer/tenant identifier (main DB)')),
                ('leave_type_code', models.CharField(db_index=True, max_length=50)),
                ('entry_type', models.CharField(choices=[('ACCRUAL', 'Accrual'), ('ALLOCATION', 'Allocation'), ('ADJUSTMENT', 'Adjustment'), ('RESERVATION', 'Reservation'), ('DEBIT', 'Debit'), ('REVERSAL', 'Reversal'), ('CARRYOVER', 'Carryover'), ('EXPIRY', 'Expiry'), ('ENCASHMENT', 'Encashment')], db_index=True, max_length=15)),
                ('amount_minutes', models.IntegerField(help_text='Positive/negative minutes; immutable once saved')),
                ('effective_date', models.DateField(default=datetime.date.today, help_text='Date the entry applies to')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.IntegerField(db_index=True, help_text='User ID from main DB')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(help_text='Employee affected by this entry', on_delete=django.db.models.deletion.CASCADE, related_name='time_off_ledger_entries', to='employees.employee')),
                ('request', models.ForeignKey(blank=True, help_text='Linked request (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='timeoff.timeoffrequest')),
            ],
            options={
                'db_table': 'timeoff_ledger_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeOffApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_index', models.IntegerField(help_text='Zero-based index of the step')),
                ('approver_user_id', models.IntegerField(db_index=True, help_text='User ID in main DB')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], db_index=True, default='PENDING', max_length=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(help_text='Request this approval belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='timeoff.timeoffrequest')),
            ],
            options={
                'db_table': 'timeoff_approvals',
                'ordering': ['request_id', 'step_index'],
            },
        ),
        migrations.AddIndex(
            model_name='timeoffrequest',
            index=models.Index(fields=['employer_id', 'employee'], name='timeoff_req_employe_236620_idx'),
        ),
        migrations.AddIndex(
            model_name='timeoffrequest',
            index=models.Index(fields=['employer_id', 'leave_type_code'], name='timeoff_req_employe_fe1323_idx'),
        ),
        migrations.AddIndex(
            model_name='timeoffrequest',
            index=models.Index(fields=['employer_id', 'status'], name='timeoff_req_employe_fbf5a9_idx'),
        ),
        migrations.AddIndex(
            model_name='timeoffrequest',
            index=models.Index(fields=['start_at', 'end_at'], name='timeoff_req_start_a_d3d835_idx'),
        ),
        migrations.AddIndex(
            model_name='timeoffledgerentry',
            index=models.Index(fields=['employer_id', 'employee'], name='timeoff_led_employe_6fc9bd_idx'),
        ),
        migrations.AddIndex(
            model_name='timeoffledgerentry',
            index=models.Index(fields=['employer_id', 'leave_type_code'], name='timeoff_led_employe_5f8dbe_idx'),
        ),
        migrations.AddIndex(
            model_name='timeoffledgerentry',
            index=models.Index(fields=['entry_type'], name='timeoff_led_entry_t_70aa5a_idx'),
        ),
        migrations.AddIndex(
            model_name='timeoffledgerentry',
            index=models.Index(fields=['effective_date'], name='timeoff_led_effecti_7f539e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timeoffapproval',
            unique_together={('request', 'step_index', 'approver_user_id')},
        ),
    ]
