# Generated by Django 5.2.9 on 2026-01-12 08:04

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from datetime import date
from decimal import Decimal
from django.db import migrations, models


def _to_decimal(value):
    if value is None:
        return None
    try:
        return Decimal(str(value))
    except Exception:
        return None


def _coerce_dates(values):
    result = []
    for val in values or []:
        if isinstance(val, date):
            result.append(val)
        else:
            try:
                result.append(date.fromisoformat(str(val)))
            except Exception:
                continue
    return result


def migrate_config_to_tables(apps, schema_editor):
    TimeOffConfiguration = apps.get_model("timeoff", "TimeOffConfiguration")
    TimeOffType = apps.get_model("timeoff", "TimeOffType")
    TimeOffApprovalStep = apps.get_model("timeoff", "TimeOffApprovalStep")
    db_alias = schema_editor.connection.alias

    for cfg in TimeOffConfiguration.objects.using(db_alias).all().iterator():
        payload = cfg.configuration or {}
        global_settings = (payload.get("global_settings") or {})
        rounding = global_settings.get("rounding") or {}
        year_end = global_settings.get("year_end_processing") or {}
        retention = global_settings.get("data_retention") or {}

        cfg.schema_version = payload.get("schema_version") or global_settings.get("schema_version") or cfg.schema_version or 2
        cfg.default_time_unit = global_settings.get("default_time_unit", cfg.default_time_unit)
        cfg.working_hours_per_day = global_settings.get("working_hours_per_day", cfg.working_hours_per_day)
        cfg.minimum_request_unit = _to_decimal(global_settings.get("minimum_request_unit")) or cfg.minimum_request_unit
        cfg.leave_year_type = global_settings.get("leave_year_type", cfg.leave_year_type)
        cfg.leave_year_start_month = global_settings.get("leave_year_start_month", cfg.leave_year_start_month)
        cfg.holiday_calendar_source = global_settings.get("holiday_calendar_source", cfg.holiday_calendar_source)
        cfg.time_zone_handling = global_settings.get("time_zone_handling", cfg.time_zone_handling)
        cfg.reservation_policy = global_settings.get("reservation_policy", cfg.reservation_policy)
        cfg.rounding_unit = rounding.get("unit", cfg.rounding_unit)
        cfg.rounding_increment_minutes = rounding.get("increment_minutes", cfg.rounding_increment_minutes)
        cfg.rounding_method = rounding.get("method", cfg.rounding_method)
        cfg.weekend_days = global_settings.get("weekend_days") or cfg.weekend_days
        cfg.module_enabled = global_settings.get("module_enabled", cfg.module_enabled)
        cfg.allow_backdated_requests = global_settings.get("allow_backdated_requests", cfg.allow_backdated_requests)
        cfg.backdated_limit_days = global_settings.get("backdated_limit_days", cfg.backdated_limit_days)
        cfg.allow_future_dated_requests = global_settings.get("allow_future_dated_requests", cfg.allow_future_dated_requests)
        cfg.future_window_days = global_settings.get("future_window_days", cfg.future_window_days)
        cfg.allow_negative_balance = global_settings.get("allow_negative_balance", cfg.allow_negative_balance)
        cfg.negative_balance_limit = global_settings.get("negative_balance_limit", cfg.negative_balance_limit)
        cfg.allow_overlapping_requests = global_settings.get("allow_overlapping_requests", cfg.allow_overlapping_requests)
        cfg.max_request_length_days = global_settings.get("max_request_length_days")
        cfg.max_requests_per_month = global_settings.get("max_requests_per_month")
        cfg.auto_reset_date = global_settings.get("auto_reset_date")
        cfg.auto_carry_forward_date = global_settings.get("auto_carry_forward_date")
        cfg.year_end_auto_reset_enabled = year_end.get("auto_reset_enabled", cfg.year_end_auto_reset_enabled)
        cfg.year_end_auto_carryover_enabled = year_end.get("auto_carryover_enabled", cfg.year_end_auto_carryover_enabled)
        cfg.year_end_process_on_month_day = year_end.get("process_on_month_day", cfg.year_end_process_on_month_day)
        cfg.request_history_years = retention.get("request_history_years", cfg.request_history_years)
        cfg.ledger_history_years = retention.get("ledger_history_years", cfg.ledger_history_years)
        cfg.save(using=db_alias)

        if TimeOffType.objects.using(db_alias).filter(configuration_id=cfg.id).exists():
            continue

        for lt in (payload.get("leave_types") or []):
            rp = lt.get("request_policy") or {}
            ap = lt.get("approval_policy") or {}
            accr = lt.get("accrual_policy") or {}
            carry = lt.get("carryover_policy") or {}
            enc = lt.get("encashment_rules") or {}
            eligibility = lt.get("eligibility") or {}

            lt_obj = TimeOffType.objects.using(db_alias).create(
                configuration=cfg,
                employer_id=cfg.employer_id,
                tenant_id=cfg.tenant_id,
                code=lt.get("code"),
                name=lt.get("name"),
                paid=lt.get("paid", True),
                color=lt.get("color"),
                description=lt.get("description"),
                mobile_enabled=lt.get("mobile_enabled", True),
                balance_visible_to_employee=lt.get("balance_visible_to_employee", True),
                allow_encashment=lt.get("allow_encashment", False),
                encashment_max_days=_to_decimal(enc.get("max_days")),
                encashment_conversion_rate=_to_decimal(enc.get("conversion_rate")) or Decimal("1.00"),
                allow_comp_off_generation=lt.get("allow_comp_off_generation", False),
                comp_off_expiry_days=lt.get("comp_off_expiry_days"),
                sandwich_rule_enabled=lt.get("sandwich_rule_enabled", False),
                eligibility_gender=eligibility.get("gender", "ALL"),
                eligibility_allowed_in_probation=eligibility.get("allowed_in_probation", True),
                eligibility_minimum_tenure_months=eligibility.get("minimum_tenure_months", 0) or 0,
                eligibility_employment_types=eligibility.get("employment_types") or [],
                eligibility_locations=eligibility.get("locations") or [],
                eligibility_departments=eligibility.get("departments") or [],
                eligibility_job_levels=eligibility.get("job_levels") or [],
                request_allow_half_day=rp.get("allow_half_day", True),
                request_allow_hourly=rp.get("allow_hourly", False),
                request_minimum_duration=_to_decimal(rp.get("minimum_duration")),
                request_maximum_duration=_to_decimal(rp.get("maximum_duration")),
                request_consecutive_days_limit=_to_decimal(rp.get("consecutive_days_limit")),
                request_allow_prefix_suffix_holidays=rp.get("allow_prefix_suffix_holidays", True),
                request_count_weekends_as_leave=rp.get("count_weekends_as_leave", False),
                request_count_holidays_as_leave=rp.get("count_holidays_as_leave", False),
                request_blackout_dates=_coerce_dates(rp.get("blackout_dates")),
                request_requires_reason=rp.get("requires_reason", True),
                request_requires_document=rp.get("requires_document", False),
                request_document_mandatory_after_days=_to_decimal(rp.get("document_mandatory_after_days")),
                approval_auto_approve=ap.get("auto_approve", False),
                approval_workflow_code=ap.get("workflow_code", "DEFAULT"),
                approval_fallback_approver=ap.get("fallback_approver", "HR"),
                approval_reminders_enabled=(ap.get("reminders") or {}).get("enabled", True),
                approval_reminder_after_hours=(ap.get("reminders") or {}).get("after_hours", 48),
                accrual_enabled=accr.get("enabled", False),
                accrual_method=accr.get("method", "MONTHLY"),
                accrual_rate_per_period=_to_decimal(accr.get("rate_per_period")) or Decimal("0.00"),
                accrual_start_trigger=accr.get("start_trigger", "DATE_OF_JOINING"),
                accrual_start_offset_days=accr.get("start_offset_days", 0) or 0,
                accrual_waiting_period_days=accr.get("waiting_period_days", 0) or 0,
                accrual_proration_method=(accr.get("proration") or {}).get("method"),
                accrual_proration_on_join=(accr.get("proration") or {}).get("on_join", True),
                accrual_proration_on_termination=(accr.get("proration") or {}).get("on_termination", True),
                accrual_cap_enabled=(accr.get("cap") or {}).get("enabled", False),
                accrual_cap_max_balance=_to_decimal((accr.get("cap") or {}).get("max_balance")),
                carryover_enabled=carry.get("enabled", False),
                carryover_max_carryover=_to_decimal(carry.get("max_carryover")),
                carryover_expires_after_days=carry.get("expires_after_days"),
            )

            for idx, step in enumerate(ap.get("steps") or []):
                TimeOffApprovalStep.objects.using(db_alias).create(
                    leave_type=lt_obj,
                    step_index=idx,
                    step_type=step.get("type", "MANAGER"),
                    required=step.get("required", True),
                )




class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employeedocument_document_type'),
        ('timeoff', '0007_timeoff_feature_expansion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOffApprovalStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_index', models.IntegerField(help_text='Zero-based index of the step')),
                ('step_type', models.CharField(help_text='MANAGER | HR | ROLE', max_length=30)),
                ('required', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'timeoff_type_approval_steps',
                'ordering': ['step_index'],
            },
        ),
        migrations.CreateModel(
            name='TimeOffType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer_id', models.IntegerField(db_index=True)),
                ('tenant_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('paid', models.BooleanField(default=True)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('mobile_enabled', models.BooleanField(default=True)),
                ('balance_visible_to_employee', models.BooleanField(default=True)),
                ('allow_encashment', models.BooleanField(default=False)),
                ('encashment_max_days', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('encashment_conversion_rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=7)),
                ('allow_comp_off_generation', models.BooleanField(default=False)),
                ('comp_off_expiry_days', models.IntegerField(blank=True, null=True)),
                ('sandwich_rule_enabled', models.BooleanField(default=False)),
                ('eligibility_gender', models.CharField(default='ALL', max_length=10)),
                ('eligibility_allowed_in_probation', models.BooleanField(default=True)),
                ('eligibility_minimum_tenure_months', models.IntegerField(default=0)),
                ('eligibility_employment_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None)),
                ('eligibility_locations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('eligibility_departments', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('eligibility_job_levels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('request_allow_half_day', models.BooleanField(default=True)),
                ('request_allow_hourly', models.BooleanField(default=False)),
                ('request_minimum_duration', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('request_maximum_duration', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('request_consecutive_days_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('request_allow_prefix_suffix_holidays', models.BooleanField(default=True)),
                ('request_count_weekends_as_leave', models.BooleanField(default=False)),
                ('request_count_holidays_as_leave', models.BooleanField(default=False)),
                ('request_blackout_dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, default=list, size=None)),
                ('request_requires_reason', models.BooleanField(default=True)),
                ('request_requires_document', models.BooleanField(default=False)),
                ('request_document_mandatory_after_days', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('approval_auto_approve', models.BooleanField(default=False)),
                ('approval_workflow_code', models.CharField(default='DEFAULT', max_length=100)),
                ('approval_fallback_approver', models.CharField(default='HR', max_length=20)),
                ('approval_reminders_enabled', models.BooleanField(default=True)),
                ('approval_reminder_after_hours', models.IntegerField(default=48)),
                ('accrual_enabled', models.BooleanField(default=False)),
                ('accrual_method', models.CharField(default='MONTHLY', max_length=30)),
                ('accrual_rate_per_period', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('accrual_start_trigger', models.CharField(default='DATE_OF_JOINING', max_length=30)),
                ('accrual_start_offset_days', models.IntegerField(default=0)),
                ('accrual_waiting_period_days', models.IntegerField(default=0)),
                ('accrual_proration_method', models.CharField(blank=True, max_length=20, null=True)),
                ('accrual_proration_on_join', models.BooleanField(default=True)),
                ('accrual_proration_on_termination', models.BooleanField(default=True)),
                ('accrual_cap_enabled', models.BooleanField(default=False)),
                ('accrual_cap_max_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('carryover_enabled', models.BooleanField(default=False)),
                ('carryover_max_carryover', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('carryover_expires_after_days', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'timeoff_types',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='timeoffconfiguration',
            name='auto_carry_forward_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeoffconfiguration',
            name='auto_reset_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeoffconfiguration',
            name='ledger_history_years',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='timeoffconfiguration',
            name='minimum_request_unit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=5),
        ),
        migrations.AddField(
            model_name='timeoffconfiguration',
            name='request_history_years',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='timeoffconfiguration',
            name='rounding_unit',
            field=models.CharField(default='MINUTES', max_length=20),
        ),
        migrations.AddField(
            model_name='timeoffconfiguration',
            name='year_end_auto_carryover_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeoffconfiguration',
            name='year_end_auto_reset_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeoffconfiguration',
            name='year_end_process_on_month_day',
            field=models.CharField(default='01-01', max_length=5),
        ),
        migrations.AlterField(
            model_name='timeoffconfiguration',
            name='configuration',
            field=models.JSONField(blank=True, default=dict, help_text='Legacy configuration snapshot (not authoritative).'),
        ),
        migrations.AlterField(
            model_name='timeoffconfiguration',
            name='schema_version',
            field=models.IntegerField(default=2, help_text='Schema version for normalization'),
        ),
        migrations.AlterField(
            model_name='timeoffconfiguration',
            name='weekend_days',
            field=models.JSONField(blank=True, default=list, help_text="Weekend names e.g. ['SATURDAY']"),
        ),
        migrations.AddIndex(
            model_name='timeoffrequest',
            index=models.Index(fields=['tenant_id'], name='timeoff_req_tenant__0cc38c_idx'),
        ),
        migrations.AddField(
            model_name='timeofftype',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='timeoff.timeoffconfiguration'),
        ),
        migrations.AddField(
            model_name='timeoffapprovalstep',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='timeoff.timeofftype'),
        ),
        migrations.RunPython(migrate_config_to_tables, reverse_code=migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='timeofftype',
            index=models.Index(fields=['tenant_id'], name='timeoff_typ_tenant__b01a7f_idx'),
        ),
        migrations.AddIndex(
            model_name='timeofftype',
            index=models.Index(fields=['employer_id', 'code'], name='timeoff_typ_employe_245906_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timeofftype',
            unique_together={('employer_id', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='timeoffapprovalstep',
            unique_together={('leave_type', 'step_index')},
        ),
    ]
