# Generated by Django 5.2.9 on 2026-01-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timeoff", "0010_remove_timeoffconfiguration_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeoffledgerentry",
            name="source_reference",
            field=models.CharField(
                blank=True,
                help_text="Human-readable source reference (e.g., request/plan/run identifier).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="timeofftype",
            name="allow_negative_balance",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="timeofftype",
            name="negative_balance_limit",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="timeofftype",
            name="reservation_policy",
            field=models.CharField(default="RESERVE_ON_SUBMIT", max_length=30),
        ),
    ]
