# Generated by Django 5.2.9 on 2026-01-26 08:50

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('employer_id', models.IntegerField(db_index=True, help_text='Tenant/employer identifier (main DB)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_plate', models.CharField(db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('ordered', 'Ordered'), ('registered', 'Registered'), ('downgraded', 'Downgraded'), ('retired', 'Retired')], default='requested', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('odometer', models.PositiveIntegerField(default=0)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fleet_vehicles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('employer_id', models.IntegerField(db_index=True, help_text='Tenant/employer identifier (main DB)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'fleet_manufacturers',
                'ordering': ['name'],
                'unique_together': {('employer_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('employer_id', models.IntegerField(db_index=True, help_text='Tenant/employer identifier (main DB)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('NORMAL', 'Normal'), ('HIGH', 'High')], default='NORMAL', max_length=10)),
                ('default_stage', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'fleet_service_types',
                'ordering': ['name'],
                'unique_together': {('employer_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('employer_id', models.IntegerField(db_index=True, help_text='Tenant/employer identifier (main DB)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('odometer', models.PositiveIntegerField(blank=True, null=True)),
                ('stage', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_final', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_records', to='fleets.servicetype')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='fleets.vehicle')),
            ],
            options={
                'db_table': 'fleet_service_records',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccidentEvent',
            fields=[
                ('employer_id', models.IntegerField(db_index=True, help_text='Tenant/employer identifier (main DB)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('driver_fault', 'Driver Fault'), ('no_fault', 'No Fault')], max_length=20)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_actual_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notes', models.TextField(blank=True, null=True)),
                ('services', models.ManyToManyField(blank=True, related_name='accidents', to='fleets.servicerecord')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accident_events', to='fleets.vehicle')),
            ],
            options={
                'db_table': 'fleet_accidents',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('employer_id', models.IntegerField(db_index=True, help_text='Tenant/employer identifier (main DB)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'fleet_model_categories',
                'ordering': ['priority', 'name'],
                'unique_together': {('employer_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='VehicleContract',
            fields=[
                ('employer_id', models.IntegerField(db_index=True, help_text='Tenant/employer identifier (main DB)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('catalog_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('residual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='active', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_contracts', to='employees.employee')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='fleets.vehicle')),
            ],
            options={
                'db_table': 'fleet_vehicle_contracts',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('employer_id', models.IntegerField(db_index=True, help_text='Tenant/employer identifier (main DB)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('BIKE', 'Bike')], max_length=10)),
                ('seating_capacity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('doors', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=50)),
                ('transmission', models.CharField(blank=True, max_length=50)),
                ('power_source', models.CharField(choices=[('FUEL', 'Fuel'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid')], default='FUEL', max_length=20)),
                ('co2_emissions', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='fleets.vehiclecategory')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='fleets.manufacturer')),
            ],
            options={
                'db_table': 'fleet_vehicle_models',
                'ordering': ['manufacturer__name', 'name'],
                'unique_together': {('manufacturer', 'name')},
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='fleets.vehiclemodel'),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('employer_id', models.IntegerField(db_index=True, help_text='Tenant/employer identifier (main DB)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('vendor_type', models.CharField(choices=[('DEALER', 'Dealer'), ('GARAGE', 'Garage'), ('REPAIR_SHOP', 'Repair Shop'), ('ACCIDENT_MANAGEMENT', 'Accident Management'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('service_types', models.ManyToManyField(blank=True, related_name='vendors', to='fleets.servicetype')),
            ],
            options={
                'db_table': 'fleet_vendors',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='fleets.vendor'),
        ),
        migrations.CreateModel(
            name='DriverAssignment',
            fields=[
                ('employer_id', models.IntegerField(db_index=True, help_text='Tenant/employer identifier (main DB)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_driver_name', models.CharField(blank=True, max_length=200)),
                ('external_driver_contact', models.CharField(blank=True, max_length=80)),
                ('assignment_type', models.CharField(choices=[('CURRENT', 'Current'), ('FUTURE', 'Future')], default='CURRENT', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('assignment_notes', models.TextField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driver_assignments', to='employees.branch')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_assignments', to='employees.employee')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='fleets.vehicle')),
            ],
            options={
                'db_table': 'fleet_driver_assignments',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['vehicle', 'assignment_type'], name='fleet_drive_vehicle_14cce6_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('employer_id', 'license_plate')},
        ),
        migrations.CreateModel(
            name='FleetSetting',
            fields=[
                ('employer_id', models.IntegerField(db_index=True, help_text='Tenant/employer identifier (main DB)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_alert_days', models.PositiveSmallIntegerField(default=30)),
                ('allow_new_requests', models.BooleanField(default=True)),
                ('notification_channels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None)),
                ('allow_requests_from_inventory_only', models.BooleanField(default=False)),
                ('default_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_default', to='fleets.vendor')),
            ],
            options={
                'db_table': 'fleet_settings',
                'unique_together': {('employer_id',)},
            },
        ),
    ]
