# Generated by Django 5.2.9 on 2026-01-17 20:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0009_employee_pin_hash_employee_rfid_tag_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer_id', models.IntegerField(db_index=True, help_text='Employer/company id from main database')),
                ('is_enabled', models.BooleanField(default=True)),
                ('allow_systray_portal', models.BooleanField(default=True)),
                ('allow_kiosk', models.BooleanField(default=True)),
                ('kiosk_mode', models.CharField(choices=[('manual', 'Manual Selection'), ('barcode_rfid', 'Barcode/RFID Only'), ('barcode_rfid_and_manual', 'Barcode/RFID + Manual')], default='barcode_rfid_and_manual', max_length=40)),
                ('barcode_source', models.CharField(blank=True, choices=[('scanner', 'Scanner'), ('front_camera', 'Front Camera'), ('back_camera', 'Back Camera')], max_length=20, null=True)),
                ('kiosk_display_seconds', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('require_pin_for_kiosk', models.BooleanField(default=False)),
                ('require_pin_for_portal', models.BooleanField(default=False)),
                ('enforce_geofence', models.BooleanField(default=True)),
                ('enforce_wifi', models.BooleanField(default=False)),
                ('enforce_geofence_on_checkout', models.BooleanField(default=True)),
                ('enforce_wifi_on_checkout', models.BooleanField(default=False)),
                ('allow_mobile_gps', models.BooleanField(default=True)),
                ('allow_ip_logging', models.BooleanField(default=True)),
                ('allow_gps_logging', models.BooleanField(default=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('auto_flag_anomalies', models.BooleanField(default=True)),
                ('max_daily_work_minutes_before_flag', models.IntegerField(blank=True, null=True)),
                ('kiosk_bypass_geofence', models.BooleanField(default=True)),
                ('kiosk_bypass_wifi', models.BooleanField(default=True)),
                ('kiosk_access_token', models.CharField(blank=True, default='', help_text='Opaque token to protect kiosk endpoints', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Configuration',
                'verbose_name_plural': 'Attendance Configurations',
                'db_table': 'attendance_configurations',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_enabled', True)), fields=('employer_id',), name='uniq_attendance_config_active_per_employer')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceLocationSite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('radius_meters', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Location Site',
                'verbose_name_plural': 'Attendance Location Sites',
                'db_table': 'attendance_location_sites',
                'indexes': [models.Index(fields=['employer_id', 'is_active'], name='attendance__employe_82d2fc_idx'), models.Index(fields=['latitude', 'longitude'], name='attendance__latitud_772766_idx')],
                'unique_together': {('employer_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WorkingSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('default_daily_minutes', models.IntegerField(default=480, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Working Schedule',
                'verbose_name_plural': 'Working Schedules',
                'db_table': 'attendance_working_schedules',
                'indexes': [models.Index(fields=['employer_id', 'is_default'], name='attendance__employe_8dbf0a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('employer_id',), name='uniq_default_working_schedule_per_employer')],
                'unique_together': {('employer_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceAllowedWifi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer_id', models.IntegerField(db_index=True)),
                ('ssid', models.CharField(max_length=255)),
                ('bssid', models.CharField(blank=True, max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wifi_networks', to='attendance.attendancelocationsite')),
            ],
            options={
                'verbose_name': 'Attendance Allowed Wi-Fi',
                'verbose_name_plural': 'Attendance Allowed Wi-Fi',
                'db_table': 'attendance_allowed_wifi',
                'indexes': [models.Index(fields=['employer_id', 'ssid'], name='attendance__employe_12728b_idx'), models.Index(fields=['employer_id', 'bssid'], name='attendance__employe_476164_idx')],
                'constraints': [models.UniqueConstraint(fields=('employer_id', 'ssid', 'bssid'), name='uniq_attendance_wifi_entry')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer_id', models.IntegerField(db_index=True)),
                ('check_in_at', models.DateTimeField()),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('worked_minutes', models.IntegerField(default=0)),
                ('expected_minutes', models.IntegerField(blank=True, null=True)),
                ('overtime_worked_minutes', models.IntegerField(default=0)),
                ('overtime_approved_minutes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('to_approve', 'To Approve'), ('approved', 'Approved'), ('refused', 'Refused')], db_index=True, default='approved', max_length=12)),
                ('mode', models.CharField(choices=[('portal_systray', 'Portal/Systray'), ('kiosk', 'Kiosk'), ('manual', 'Manual')], db_index=True, default='portal_systray', max_length=20)),
                ('check_in_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('check_in_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('check_in_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('check_in_wifi_ssid', models.CharField(blank=True, max_length=255, null=True)),
                ('check_in_wifi_bssid', models.CharField(blank=True, max_length=64, null=True)),
                ('check_out_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('check_out_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('check_out_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('check_out_wifi_ssid', models.CharField(blank=True, max_length=255, null=True)),
                ('check_out_wifi_bssid', models.CharField(blank=True, max_length=64, null=True)),
                ('anomaly_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('kiosk_session_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_in_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_in_records', to='attendance.attendancelocationsite')),
                ('check_out_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_out_records', to='attendance.attendancelocationsite')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'attendance_records',
                'ordering': ['-check_in_at'],
                'indexes': [models.Index(fields=['employer_id', 'employee'], name='attendance__employe_f2192c_idx'), models.Index(fields=['status'], name='attendance__status_5b1243_idx'), models.Index(fields=['mode'], name='attendance__mode_02d5d5_idx'), models.Index(fields=['check_in_at'], name='attendance__check_i_dc8e86_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('check_out_at__isnull', True)), fields=('employee',), name='uniq_open_attendance_record_per_employee'), models.CheckConstraint(condition=models.Q(('check_out_at__gt', models.F('check_in_at')), ('check_out_at__isnull', True), _connector='OR'), name='attendance_checkout_after_checkin')],
            },
        ),
        migrations.CreateModel(
            name='WorkingScheduleDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_minutes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('expected_minutes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='attendance.workingschedule')),
            ],
            options={
                'verbose_name': 'Working Schedule Day',
                'verbose_name_plural': 'Working Schedule Days',
                'db_table': 'attendance_working_schedule_days',
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='working_schedule_day_end_after_start')],
                'unique_together': {('schedule', 'weekday')},
            },
        ),
    ]
