# Generated by Django 5.2.8 on 2026-01-16 20:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0007_alter_employeedocument_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer_id', models.IntegerField(db_index=True, help_text='Employer ID from main database')),
                ('date', models.DateField(db_index=True)),
                ('first_in_at', models.DateTimeField(blank=True, null=True)),
                ('last_out_at', models.DateTimeField(blank=True, null=True)),
                ('worked_minutes', models.IntegerField(default=0)),
                ('late_minutes', models.IntegerField(default=0)),
                ('early_leave_minutes', models.IntegerField(default=0)),
                ('overtime_minutes', models.IntegerField(default=0)),
                ('approved_overtime_minutes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('PARTIAL', 'Partial'), ('ON_LEAVE', 'On Leave'), ('HOLIDAY', 'Holiday'), ('WEEKEND', 'Weekend'), ('REST_DAY', 'Rest Day')], default='ABSENT', max_length=20)),
                ('anomaly_flags', models.JSONField(blank=True, default=list)),
                ('locked_for_payroll', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_days', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Attendance Day',
                'verbose_name_plural': 'Attendance Days',
                'db_table': 'attendance_days',
            },
        ),
        migrations.CreateModel(
            name='AttendanceDayAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('LOCKED', 'Locked for Payroll'), ('UNLOCKED', 'Unlocked for Payroll')], max_length=20)),
                ('performed_by_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('attendance_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='attendance.attendanceday')),
            ],
            options={
                'verbose_name': 'Attendance Day Audit Log',
                'verbose_name_plural': 'Attendance Day Audit Logs',
                'db_table': 'attendance_day_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer_id', models.IntegerField(db_index=True, help_text='Employer ID from main database')),
                ('name', models.CharField(max_length=255)),
                ('device_type', models.CharField(choices=[('RFID', 'RFID'), ('BIOMETRIC', 'Biometric'), ('KIOSK', 'Kiosk')], max_length=20)),
                ('auth_token', models.CharField(blank=True, max_length=255, null=True)),
                ('public_key', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.branch')),
            ],
            options={
                'verbose_name': 'Attendance Device',
                'verbose_name_plural': 'Attendance Devices',
                'db_table': 'attendance_devices',
                'unique_together': {('employer_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DeviceEventIngestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('parsed_ok', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingest_logs', to='attendance.attendancedevice')),
            ],
            options={
                'verbose_name': 'Device Event Ingest Log',
                'verbose_name_plural': 'Device Event Ingest Logs',
                'db_table': 'attendance_device_ingest_logs',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer_id', models.IntegerField(db_index=True, help_text='Employer ID from main database')),
                ('name', models.CharField(max_length=200)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_minutes', models.IntegerField(default=0)),
                ('late_grace_minutes', models.IntegerField(default=0)),
                ('early_grace_minutes', models.IntegerField(default=0)),
                ('overtime_starts_after_minutes', models.IntegerField(default=0)),
                ('requires_checkout', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.branch')),
            ],
            options={
                'verbose_name': 'Shift Template',
                'verbose_name_plural': 'Shift Templates',
                'db_table': 'attendance_shift_templates',
                'ordering': ['name'],
                'unique_together': {('employer_id', 'name')},
            },
        ),
        migrations.AddField(
            model_name='attendanceday',
            name='expected_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.shifttemplate'),
        ),
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer_id', models.IntegerField(db_index=True, help_text='Employer ID from main database')),
                ('attendance_date', models.DateField(db_index=True, help_text='Shift start date for this event')),
                ('timestamp', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('IN', 'Check In'), ('OUT', 'Check Out'), ('BREAK_START', 'Break Start'), ('BREAK_END', 'Break End')], max_length=20)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('MOBILE', 'Mobile'), ('WEB', 'Web'), ('DEVICE', 'Device'), ('IMPORT', 'Import'), ('KIOSK', 'Kiosk')], max_length=20)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.attendancedevice')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_events', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Attendance Event',
                'verbose_name_plural': 'Attendance Events',
                'db_table': 'attendance_events',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['employer_id', 'employee', 'attendance_date'], name='attendance__employe_fb3983_idx'), models.Index(fields=['timestamp'], name='attendance__timesta_28934c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer_id', models.IntegerField(db_index=True, help_text='Employer ID from main database')),
                ('scope_type', models.CharField(choices=[('GLOBAL', 'Global'), ('BRANCH', 'Branch'), ('DEPARTMENT', 'Department'), ('EMPLOYEE', 'Employee')], default='GLOBAL', max_length=20)),
                ('schema_version', models.IntegerField(default=1)),
                ('policy', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.branch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.department')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
            options={
                'verbose_name': 'Attendance Policy',
                'verbose_name_plural': 'Attendance Policies',
                'db_table': 'attendance_policies',
                'indexes': [models.Index(fields=['employer_id', 'scope_type'], name='attendance__employe_930f67_idx'), models.Index(fields=['employer_id', 'branch'], name='attendance__employe_92f1e1_idx'), models.Index(fields=['employer_id', 'department'], name='attendance__employe_961631_idx'), models.Index(fields=['employer_id', 'employee'], name='attendance__employe_a2ee72_idx')],
            },
        ),
        migrations.CreateModel(
            name='OvertimeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer_id', models.IntegerField(db_index=True, help_text='Employer ID from main database')),
                ('date', models.DateField(db_index=True)),
                ('minutes', models.IntegerField(default=0)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approved_by_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_requests', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Overtime Request',
                'verbose_name_plural': 'Overtime Requests',
                'db_table': 'attendance_overtime_requests',
                'indexes': [models.Index(fields=['employer_id', 'employee', 'date'], name='attendance__employe_7a0ef9_idx'), models.Index(fields=['status'], name='attendance__status_c64c39_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employer_id', models.IntegerField(db_index=True, help_text='Employer ID from main database')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField(blank=True, null=True)),
                ('weekdays', models.JSONField(blank=True, default=list, help_text='List of weekday numbers (0=Mon..6=Sun); empty means all days.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='employees.employee')),
                ('shift_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='attendance.shifttemplate')),
            ],
            options={
                'verbose_name': 'Employee Schedule',
                'verbose_name_plural': 'Employee Schedules',
                'db_table': 'attendance_employee_schedules',
                'indexes': [models.Index(fields=['employer_id', 'employee'], name='attendance__employe_e3c2f4_idx'), models.Index(fields=['date_from', 'date_to'], name='attendance__date_fr_cc829a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='attendanceday',
            index=models.Index(fields=['employer_id', 'date'], name='attendance__employe_5440e6_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceday',
            index=models.Index(fields=['employer_id', 'employee'], name='attendance__employe_a54327_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceday',
            index=models.Index(fields=['status'], name='attendance__status_e79ccf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendanceday',
            unique_together={('employee', 'date')},
        ),
    ]
