# Generated by Django 5.2.8 on 2026-01-16 21:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancepolicy',
            name='geo_allowed_locations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, help_text='List of allowed coordinates or location identifiers.', null=True, size=None),
        ),
    ]
