# Generated by Codex on 2026-01-16

from datetime import date

from django.contrib.postgres.fields import ArrayField
from django.db import migrations, models


def _get_nested(data, path):
    current = data
    for key in path:
        if not isinstance(current, dict) or key not in current:
            return False, None
        current = current[key]
    return True, current


def _coerce_dates(values):
    if values is None:
        return None
    output = []
    for item in values:
        if isinstance(item, date):
            output.append(item)
            continue
        try:
            output.append(date.fromisoformat(str(item)))
        except Exception:
            continue
    return output


def _migrate_policy_data(apps, schema_editor):
    AttendancePolicy = apps.get_model("attendance", "AttendancePolicy")
    ShiftTemplate = apps.get_model("attendance", "ShiftTemplate")
    db_alias = schema_editor.connection.alias

    for policy in AttendancePolicy.objects.using(db_alias).all():
        data = policy.policy or {}
        updates = {}

        exists, value = _get_nested(data, ["working_calendar", "timezone"])
        if exists:
            updates["working_timezone"] = value

        exists, value = _get_nested(data, ["working_calendar", "working_days"])
        if exists:
            updates["working_days"] = value

        exists, value = _get_nested(data, ["working_calendar", "weekend_days"])
        if exists:
            updates["weekend_days"] = value

        exists, value = _get_nested(data, ["working_calendar", "holiday_calendar_source"])
        if exists:
            updates["holiday_calendar_source"] = value

        exists, value = _get_nested(data, ["working_calendar", "holiday_dates"])
        if exists:
            updates["holiday_dates"] = _coerce_dates(value)

        exists, value = _get_nested(data, ["working_calendar", "special_days"])
        if exists:
            updates["special_days"] = _coerce_dates(value)

        exists, value = _get_nested(data, ["attendance_policy", "allow_self_check_in"])
        if exists:
            updates["allow_self_check_in"] = value

        exists, value = _get_nested(data, ["attendance_policy", "allow_manual_edits"])
        if exists:
            updates["allow_manual_edits"] = value

        exists, value = _get_nested(data, ["attendance_policy", "allow_device_only"])
        if exists:
            updates["allow_device_only"] = value

        exists, value = _get_nested(data, ["attendance_policy", "max_early_check_in_minutes"])
        if exists:
            updates["max_early_check_in_minutes"] = value

        exists, value = _get_nested(data, ["attendance_policy", "max_late_check_out_minutes"])
        if exists:
            updates["max_late_check_out_minutes"] = value

        exists, value = _get_nested(data, ["attendance_policy", "duplicate_punch_handling"])
        if exists:
            updates["duplicate_punch_handling"] = value

        exists, value = _get_nested(data, ["attendance_policy", "missing_punch_handling"])
        if exists:
            updates["missing_punch_handling"] = value

        exists, value = _get_nested(data, ["attendance_policy", "allow_employee_correction"])
        if exists:
            updates["allow_employee_correction"] = value

        exists, value = _get_nested(data, ["attendance_policy", "late_grace_minutes"])
        if exists:
            updates["late_grace_minutes"] = value

        exists, value = _get_nested(data, ["attendance_policy", "early_grace_minutes"])
        if exists:
            updates["early_grace_minutes"] = value

        exists, value = _get_nested(data, ["attendance_policy", "rounding"])
        if exists and isinstance(value, dict):
            if "unit" in value:
                updates["rounding_unit"] = value.get("unit")
            if "increment" in value:
                updates["rounding_increment"] = value.get("increment")
            if "method" in value:
                updates["rounding_method"] = value.get("method")
            if "in_rounding" in value:
                updates["rounding_in_rounding"] = value.get("in_rounding")
            if "out_rounding" in value:
                updates["rounding_out_rounding"] = value.get("out_rounding")

        exists, value = _get_nested(data, ["attendance_policy", "require_edit_reason"])
        if exists:
            updates["require_edit_reason"] = value

        exists, value = _get_nested(data, ["attendance_policy", "edit_approval_after_days"])
        if exists:
            updates["edit_approval_after_days"] = value

        exists, value = _get_nested(data, ["overtime_policy", "starts_after_minutes"])
        if exists:
            updates["overtime_starts_after_minutes"] = value

        exists, value = _get_nested(data, ["overtime_policy", "minimum_minutes"])
        if exists:
            updates["overtime_minimum_minutes"] = value

        exists, value = _get_nested(data, ["overtime_policy", "require_approval"])
        if exists:
            updates["overtime_require_approval"] = value

        exists, value = _get_nested(data, ["overtime_policy", "rate_categories"])
        if exists and isinstance(value, dict):
            if "WEEKDAY" in value:
                updates["overtime_rate_weekday"] = value.get("WEEKDAY")
            if "WEEKEND" in value:
                updates["overtime_rate_weekend"] = value.get("WEEKEND")
            if "HOLIDAY" in value:
                updates["overtime_rate_holiday"] = value.get("HOLIDAY")

        exists, value = _get_nested(data, ["overtime_policy", "max_overtime_minutes_per_day"])
        if exists:
            updates["max_overtime_minutes_per_day"] = value

        exists, value = _get_nested(data, ["shift_policy", "assignment_strategy"])
        if exists:
            updates["shift_assignment_strategy"] = value

        exists, value = _get_nested(data, ["shift_policy", "default_shift_template_id"])
        if exists and value:
            shift = ShiftTemplate.objects.using(db_alias).filter(id=value).first()
            if shift:
                updates["default_shift_template_id"] = shift.id

        exists, value = _get_nested(data, ["payroll_mapping", "count_worked_minutes"])
        if exists:
            updates["payroll_count_worked_minutes"] = value

        exists, value = _get_nested(data, ["payroll_mapping", "count_approved_overtime_only"])
        if exists:
            updates["payroll_count_approved_overtime_only"] = value

        exists, value = _get_nested(data, ["payroll_mapping", "late_penalty_mode"])
        if exists:
            updates["payroll_late_penalty_mode"] = value

        exists, value = _get_nested(data, ["payroll_mapping", "absence_penalty_mode"])
        if exists:
            updates["payroll_absence_penalty_mode"] = value

        exists, value = _get_nested(data, ["geo_rules", "enabled"])
        if exists:
            updates["geo_enabled"] = value

        exists, value = _get_nested(data, ["geo_rules", "radius_meters"])
        if exists:
            updates["geo_radius_meters"] = value

        exists, value = _get_nested(data, ["geo_rules", "allowed_locations"])
        if exists:
            updates["geo_allowed_locations"] = value

        if updates:
            AttendancePolicy.objects.using(db_alias).filter(id=policy.id).update(**updates)


def _noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancepolicy",
            name="working_timezone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="working_days",
            field=ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="weekend_days",
            field=ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="holiday_calendar_source",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="holiday_dates",
            field=ArrayField(base_field=models.DateField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="special_days",
            field=ArrayField(base_field=models.DateField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="allow_self_check_in",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="allow_manual_edits",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="allow_device_only",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="max_early_check_in_minutes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="max_late_check_out_minutes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="duplicate_punch_handling",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="missing_punch_handling",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="allow_employee_correction",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="late_grace_minutes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="early_grace_minutes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="rounding_unit",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="rounding_increment",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="rounding_method",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="rounding_in_rounding",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="rounding_out_rounding",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="require_edit_reason",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="edit_approval_after_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="overtime_starts_after_minutes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="overtime_minimum_minutes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="overtime_require_approval",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="overtime_rate_weekday",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="overtime_rate_weekend",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="overtime_rate_holiday",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="max_overtime_minutes_per_day",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="shift_assignment_strategy",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="default_shift_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.SET_NULL,
                related_name="default_policy_for",
                to="attendance.shifttemplate",
            ),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="payroll_count_worked_minutes",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="payroll_count_approved_overtime_only",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="payroll_late_penalty_mode",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="payroll_absence_penalty_mode",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="geo_enabled",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="geo_radius_meters",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancepolicy",
            name="geo_allowed_locations",
            field=ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
        migrations.RunPython(_migrate_policy_data, _noop_reverse),
        migrations.RemoveField(
            model_name="attendancepolicy",
            name="policy",
        ),
    ]
