# Generated by Django 5.2.8 on 2026-01-16 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendancepolicy_geo_allowed_locations'),
        ('attendance', '0002_attendance_policy_columns'),
    ]

    operations = [
    ]
