# Generated by Codex on 2026-01-16

import django.db.models.deletion
import uuid
from django.db import migrations, models


def _generate_token():
    return uuid.uuid4().hex


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0002_attendance_policy_columns"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceKioskSettings",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("employer_id", models.IntegerField(db_index=True, help_text="Employer ID from main database")),
                (
                    "kiosk_mode",
                    models.CharField(
                        choices=[("BARCODE_RFID", "Barcode/RFID"), ("MANUAL", "Manual"), ("BOTH", "Both")],
                        default="BOTH",
                        max_length=20,
                    ),
                ),
                (
                    "barcode_source",
                    models.CharField(
                        choices=[("SCANNER", "Scanner"), ("FRONT_CAMERA", "Front Camera"), ("BACK_CAMERA", "Back Camera")],
                        default="SCANNER",
                        max_length=20,
                    ),
                ),
                ("display_time_seconds", models.IntegerField(default=3)),
                ("pin_required", models.BooleanField(default=False)),
                ("kiosk_url_token", models.CharField(default=_generate_token, max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Attendance Kiosk Settings",
                "verbose_name_plural": "Attendance Kiosk Settings",
                "db_table": "attendance_kiosk_settings",
                "unique_together": {("employer_id",)},
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("employer_id", models.IntegerField(db_index=True, help_text="Employer ID from main database")),
                ("check_in_at", models.DateTimeField()),
                ("check_out_at", models.DateTimeField(blank=True, null=True)),
                ("worked_minutes", models.IntegerField(default=0)),
                ("extra_minutes", models.IntegerField(default=0)),
                (
                    "overtime_status",
                    models.CharField(
                        choices=[("TO_APPROVE", "To Approve"), ("APPROVED", "Approved"), ("REFUSED", "Refused")],
                        default="TO_APPROVE",
                        max_length=20,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("SYSTRAY", "Systray"), ("KIOSK", "Kiosk"), ("MANUAL", "Manual")],
                        default="SYSTRAY",
                        max_length=20,
                    ),
                ),
                ("ip_check_in", models.GenericIPAddressField(blank=True, null=True)),
                ("ip_check_out", models.GenericIPAddressField(blank=True, null=True)),
                ("gps_check_in_lat", models.FloatField(blank=True, null=True)),
                ("gps_check_in_lng", models.FloatField(blank=True, null=True)),
                ("gps_check_out_lat", models.FloatField(blank=True, null=True)),
                ("gps_check_out_lng", models.FloatField(blank=True, null=True)),
                ("created_by_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="employees.employee",
                    ),
                ),
                (
                    "kiosk_device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_records",
                        to="attendance.attendancedevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
                "db_table": "attendance_records",
            },
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(fields=["employer_id", "employee"], name="attendance__employe_0d88f5_idx"),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(fields=["check_in_at"], name="attendance__check_i_3a7dc6_idx"),
        ),
        migrations.AddIndex(
            model_name="attendancerecord",
            index=models.Index(fields=["overtime_status"], name="attendance__overtim_15a8a2_idx"),
        ),
    ]
