# Generated by Codex on 2026-01-16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0003_add_attendance_records_kiosk_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="overtime_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
