# Generated by Django 5.2.8 on 2026-01-16 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_add_attendance_records_kiosk_settings'),
        ('attendance', '0003_merge_20260116_2248'),
    ]

    operations = [
    ]
