# Generated by Django 5.2.9 on 2026-01-18 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_branch_kiosk_stations'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendanceallowedwifi',
            new_name='attendance__employe_33ab35_idx',
            old_name='attendance_wifi_branch_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancekioskstation',
            new_name='attendance__employe_b02fc2_idx',
            old_name='attendance_kiosk_station_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancelocationsite',
            new_name='attendance__employe_0eb7ed_idx',
            old_name='attendance_site_branch_idx',
        ),
    ]
