# Generated by Django 5.2.8 on 2026-01-16 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_add_overtime_reason'),
        ('attendance', '0004_merge_20260116_2348'),
    ]

    operations = [
    ]
